import type { backendInterface, Signal, PaymentPublic, SubscriptionPublic, UpiConfigPublic } from "../backend";
import { SignalType, TradeStatus, UserRole, Variant_success_failed, CertificateStatus } from "../backend";
import { PaymentStatus } from "../types";
import type { CertificateRequestPublic, MasterTemplate } from "../types";
import type { Principal } from "@icp-sdk/core/principal";

const mockPrincipal = { toText: () => "user-mock-principal" } as Principal;

const now = BigInt(Date.now()) * BigInt(1_000_000);
const oneDayNs = BigInt(24 * 60 * 60 * 1_000_000_000);

const mockSignals: Signal[] = [
  {
    id: BigInt(1),
    pair: "EUR/USD",
    signalType: SignalType.buy,
    entryPrice: 1.12,
    stopLoss: 1.0926,
    takeProfit: 1.1476,
    confidence: BigInt(95),
    isActive: true,
    timestamp: now,
    tradeStatus: TradeStatus.success,
  },
  {
    id: BigInt(2),
    pair: "GBP/JPY",
    signalType: SignalType.sell,
    entryPrice: 0.6828,
    stopLoss: 0.2328,
    takeProfit: 0.485,
    confidence: BigInt(95),
    isActive: true,
    timestamp: now - BigInt(3600_000_000_000),
    tradeStatus: TradeStatus.failed,
  },
  {
    id: BigInt(3),
    pair: "BTC/USD",
    signalType: SignalType.buy,
    entryPrice: 0.1,
    stopLoss: 0.3,
    takeProfit: 0.19,
    confidence: BigInt(90),
    isActive: true,
    timestamp: now - BigInt(7200_000_000_000),
    tradeStatus: TradeStatus.pending,
  },
  {
    id: BigInt(4),
    pair: "EUR/USD",
    signalType: SignalType.sell,
    entryPrice: 0.37,
    stopLoss: 0.2593,
    takeProfit: 0.37,
    confidence: BigInt(90),
    isActive: true,
    timestamp: now - BigInt(10800_000_000_000),
    tradeStatus: TradeStatus.pending,
  },
];

const mockPayments: PaymentPublic[] = [
  {
    id: BigInt(1),
    userId: mockPrincipal,
    status: PaymentStatus.pending,
    utrNumber: "UTR123456789",
    senderName: "Rahul Sharma",
    timestamp: now - BigInt(3600_000_000_000),
    screenshotBlob: {
      getBytes: async () => new Uint8Array(),
      getDirectURL: () => "https://placehold.co/200x200",
      withUploadProgress: function() { return this; },
    } as any,
  },
  {
    id: BigInt(2),
    userId: mockPrincipal,
    status: PaymentStatus.approved,
    utrNumber: "UTR987654321",
    senderName: "Priya Verma",
    timestamp: now - BigInt(86400_000_000_000),
    screenshotBlob: {
      getBytes: async () => new Uint8Array(),
      getDirectURL: () => "https://placehold.co/200x200",
      withUploadProgress: function() { return this; },
    } as any,
  },
];

const mockSubscription: SubscriptionPublic = {
  userId: mockPrincipal,
  isActive: true,
  expiresAt: now + oneDayNs,
};

const mockUpiConfig: UpiConfigPublic = {
  upiId: "tradingsignals@upi",
  qrCodeBlob: undefined,
};

const mockBlob = (url = "https://placehold.co/400x280") => ({
  getBytes: async () => new Uint8Array(),
  getDirectURL: () => url,
  withUploadProgress: function() { return this; },
} as any);

const mockCertificates: CertificateRequestPublic[] = [
  {
    id: BigInt(1),
    userId: "user-mock-principal",
    fullName: "Rahul Sharma",
    state: "Maharashtra",
    country: "India",
    email: "rahul@example.com",
    experience: "Intermediate",
    paymentAmount: 99,
    utrNumber: "CERT123456",
    status: CertificateStatus.approved,
    certCode: "TSP-2024-001",
    autoGenerated: true,
    autoInjectData: {
      fullName: "Rahul Sharma",
      issueDate: "12 Apr 2024",
      certCode: "TSP-2024-001",
    },
    createdAt: now - BigInt(7 * 24 * 3600_000_000_000),
    updatedAt: now - BigInt(2 * 24 * 3600_000_000_000),
  },
  {
    id: BigInt(2),
    userId: "user-mock-principal",
    fullName: "Priya Verma",
    state: "Delhi",
    country: "India",
    email: "priya@example.com",
    experience: "Advanced",
    paymentAmount: 99,
    utrNumber: "CERT789012",
    status: CertificateStatus.pending,
    certCode: "TSP-2024-002",
    autoGenerated: false,
    createdAt: now - BigInt(2 * 24 * 3600_000_000_000),
    updatedAt: now - BigInt(1 * 24 * 3600_000_000_000),
  },
  {
    id: BigInt(3),
    userId: "user-mock-principal",
    fullName: "Amit Kumar",
    state: "Karnataka",
    country: "India",
    experience: "Beginner",
    paymentAmount: 99,
    utrNumber: "CERT345678",
    status: CertificateStatus.rejected,
    rejectionReason: "Payment verification failed. Please resubmit with clear UTR screenshot.",
    certCode: "TSP-2024-003",
    autoGenerated: false,
    createdAt: now - BigInt(14 * 24 * 3600_000_000_000),
    updatedAt: now - BigInt(10 * 24 * 3600_000_000_000),
  },
];

let masterTemplate: MasterTemplate | null = null;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const mockBackend = {
  _immutableObjectStorageBlobsAreLive: async (_hashes) => [],
  _immutableObjectStorageBlobsToDelete: async () => [],
  _immutableObjectStorageConfirmBlobDeletion: async (_blobs) => undefined,
  _immutableObjectStorageCreateCertificate: async (_hash) => ({ method: "", blob_hash: "" }),
  _immutableObjectStorageRefillCashier: async (_info) => ({}),
  _immutableObjectStorageUpdateGatewayPrincipals: async () => undefined,
  _initializeAccessControl: async () => undefined,
  activateUserSubscription: async (_userId) => undefined,
  addSignal: async (input) => ({
    id: BigInt(Date.now()),
    pair: input.pair,
    signalType: input.signalType,
    entryPrice: input.entryPrice,
    stopLoss: input.stopLoss,
    takeProfit: input.takeProfit,
    confidence: input.confidence,
    isActive: true,
    timestamp: BigInt(Date.now()) * BigInt(1_000_000),
    tradeStatus: TradeStatus.pending,
  }),
  approvePayment: async (_id) => true,
  assignCallerUserRole: async (_user, _role) => undefined,
  checkSubscriptionStatus: async () => true,
  deleteSignal: async (_id) => true,
  getCallerUserRole: async () => UserRole.user,
  getMyPayments: async () => mockPayments,
  getMySubscription: async () => mockSubscription,
  getUpiConfig: async () => mockUpiConfig,
  isCallerAdmin: async () => false,
  listAllPayments: async () => mockPayments,
  listSignals: async () => mockSignals,
  markTradeOutcome: async (id, status, _proofKey) => ({
    ...mockSignals[0],
    id,
    tradeStatus: status === Variant_success_failed.success ? TradeStatus.success : TradeStatus.failed,
  }),
  rejectPayment: async (_id, _reason) => true,
  selfRegister: async () => undefined,
  submitPayment: async (_blob, _utr, _senderName) => mockPayments[0],
  updateQrCode: async (_blob) => undefined,
  updateSignal: async (_id, _input) => true,
  updateUpiId: async (_upiId) => undefined,
  verifyAdminPassword: (_password: string) => Promise.resolve(false),
  getActiveSubscriberCount: async () => BigInt(42),
  getTradeStats: async () => ({
    totalSignals: BigInt(120),
    successSignals: BigInt(96),
    failedSignals: BigInt(24),
    winRate: 0.8,
  }),
  listPublicSuccessSignals: async () => mockSignals.filter(s => s.tradeStatus === TradeStatus.success),
  claimAdminRole: async (_password: string) => false,

  // Certificate methods
  submitCertificateRequest: async (
    _fullName, _state, _country, _email, _experience,
    _screenshot1, _screenshot2, _paymentScreenshot, _utr
  ) => ({
    ...mockCertificates[1],
    id: BigInt(Date.now()),
    certCode: `TSP-${new Date().getFullYear()}-${String(Date.now()).slice(-4)}`,
    createdAt: BigInt(Date.now()) * BigInt(1_000_000),
    updatedAt: BigInt(Date.now()) * BigInt(1_000_000),
  }),

  getMyCertificates: async () => mockCertificates,

  hasCertificate: async () => true,

  verifyCertificate: async (certCode: string) => {
    const found = mockCertificates.find(c => c.certCode === certCode && c.status === CertificateStatus.approved);
    return found ?? null;
  },

  approveCertificate: async (id: bigint, customBlob?: any) => {
    const cert = mockCertificates.find(c => c.id === id);
    if (!cert) return false;
    cert.status = CertificateStatus.approved;
    if (customBlob) {
      cert.autoGenerated = false;
      cert.certificate = mockBlob();
    } else {
      cert.autoGenerated = true;
      cert.autoInjectData = {
        fullName: cert.fullName,
        issueDate: new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }),
        certCode: cert.certCode,
      };
    }
    return true;
  },

  rejectCertificate: async (id: bigint, reason?: string) => {
    const cert = mockCertificates.find(c => c.id === id);
    if (!cert) return false;
    cert.status = CertificateStatus.rejected;
    cert.rejectionReason = reason;
    return true;
  },

  listAllCertificateRequests: async () => mockCertificates,

  updateMasterTemplate: async (_blob: any) => {
    masterTemplate = { blob: mockBlob("https://placehold.co/800x600?text=Certificate+Template"), updatedAt: BigInt(Date.now()) * BigInt(1_000_000) };
    return undefined;
  },

  getMasterTemplate: async () => masterTemplate,
} as unknown as backendInterface;
