import { ExternalBlob } from "@/backend";
import { GoldenTickBadge } from "@/components/GoldenTickBadge";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { useBackend } from "@/hooks/useBackend";
import { useCertificateStatus } from "@/hooks/useCertificateStatus";
import type { CertificateRequestPublic, UpiConfigPublic } from "@/types";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  AlertCircle,
  Award,
  CheckCircle2,
  Clock,
  Copy,
  Download,
  Hash,
  ImageIcon,
  Loader2,
  Star,
  Upload,
  XCircle,
} from "lucide-react";
import { useCallback, useRef, useState } from "react";
import { toast } from "sonner";

const DEFAULT_UPI_ID = "6203460064@ptsbi";
const DEFAULT_QR_URL = "/assets/qr-code.jpg";

function formatDate(ns: bigint) {
  return new Date(Number(ns / 1_000_000n)).toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

// ---- File Drop Zone ----
interface DropZoneProps {
  file: File | null;
  onFile: (f: File) => void;
  label: string;
  required?: boolean;
  disabled?: boolean;
}
function DropZone({ file, onFile, label, required, disabled }: DropZoneProps) {
  const ref = useRef<HTMLInputElement>(null);
  const [drag, setDrag] = useState(false);
  function pick(f: File) {
    if (f.size > 5 * 1024 * 1024) {
      toast.error("Image too large. Max 5 MB.");
      return;
    }
    onFile(f);
  }
  return (
    <button
      type="button"
      disabled={disabled}
      className={`w-full border-2 border-dashed rounded-xl p-4 text-center transition-all duration-200 ${
        disabled
          ? "opacity-50 cursor-not-allowed border-border"
          : drag
            ? "border-primary bg-primary/8"
            : file
              ? "border-emerald-500/50 bg-emerald-500/5"
              : "border-border hover:border-primary/50 hover:bg-primary/4"
      }`}
      onClick={() => !disabled && ref.current?.click()}
      onDragOver={(e) => {
        e.preventDefault();
        if (!disabled) setDrag(true);
      }}
      onDragLeave={() => setDrag(false)}
      onDrop={(e) => {
        e.preventDefault();
        setDrag(false);
        const f = e.dataTransfer.files[0];
        if (f?.type.startsWith("image/")) pick(f);
      }}
    >
      <input
        ref={ref}
        type="file"
        accept="image/*"
        className="hidden"
        disabled={disabled}
        onChange={(e) => {
          const f = e.target.files?.[0];
          if (f) pick(f);
        }}
      />
      {file ? (
        <div className="flex items-center gap-2 justify-center">
          <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
          <p className="text-xs font-medium text-foreground truncate">
            {file.name}
          </p>
        </div>
      ) : (
        <div className="flex items-center gap-2 justify-center">
          <ImageIcon className="w-4 h-4 text-muted-foreground shrink-0" />
          <p className="text-xs text-muted-foreground">
            {label}
            {required && <span className="text-destructive ml-1">*</span>} ·
            click/drag
          </p>
        </div>
      )}
    </button>
  );
}

// ---- Cert Status Badge ----
function CertStatusBadge({ status }: { status: string }) {
  if (status === "approved")
    return (
      <StatusBadge variant="approved" className="gap-1">
        <CheckCircle2 className="w-3 h-3" /> APPROVED
      </StatusBadge>
    );
  if (status === "rejected")
    return (
      <StatusBadge variant="rejected" className="gap-1">
        <XCircle className="w-3 h-3" /> REJECTED
      </StatusBadge>
    );
  return (
    <StatusBadge variant="pending" className="gap-1">
      <Clock className="w-3 h-3" /> PENDING
    </StatusBadge>
  );
}

// ---- Certificate Card ----
function CertificateCard({ cert }: { cert: CertificateRequestPublic }) {
  const [dl, setDl] = useState(false);
  const { actor, isReady } = useBackend();

  async function downloadAutoGenerated(d: {
    fullName: string;
    issueDate: string;
    certCode: string;
  }) {
    // Fetch master template URL from backend
    const a = actor as unknown as Record<string, unknown>;
    if (typeof a.getMasterTemplate !== "function") {
      toast.error("Template not configured — contact admin");
      return;
    }
    const template = await (
      a.getMasterTemplate as () => Promise<{
        blob?: { getDirectURL: () => string };
      } | null>
    )();
    if (!template?.blob) {
      toast.error("Template not configured — contact admin");
      return;
    }

    const templateUrl = template.blob.getDirectURL();
    const img = new Image();
    img.crossOrigin = "anonymous";

    await new Promise<void>((resolve, reject) => {
      img.onload = () => resolve();
      img.onerror = () => reject(new Error("Failed to load template image"));
      img.src = templateUrl;
    });

    const canvas = document.createElement("canvas");
    canvas.width = img.naturalWidth;
    canvas.height = img.naturalHeight;
    const ctx = canvas.getContext("2d");
    if (!ctx) throw new Error("Canvas not available");

    // Draw template
    ctx.drawImage(img, 0, 0);

    // Text overlay — white/gold on dark template
    const w = canvas.width;
    const h = canvas.height;

    // Full name — large, centered, lower-center region
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    ctx.font = `bold ${Math.round(h * 0.065)}px Georgia, serif`;
    ctx.fillStyle = "#F59E0B"; // gold
    ctx.shadowColor = "rgba(0,0,0,0.7)";
    ctx.shadowBlur = 8;
    ctx.fillText(d.fullName, w / 2, h * 0.58);

    // Issue date — smaller, below name
    ctx.font = `${Math.round(h * 0.032)}px Georgia, serif`;
    ctx.fillStyle = "#FFFFFF";
    ctx.shadowBlur = 5;
    ctx.fillText(d.issueDate, w / 2, h * 0.67);

    // Certificate ID — monospace, footer area
    ctx.font = `${Math.round(h * 0.024)}px Courier New, monospace`;
    ctx.fillStyle = "rgba(255,255,255,0.75)";
    ctx.shadowBlur = 3;
    ctx.fillText(`Certificate ID: ${d.certCode}`, w / 2, h * 0.88);

    // Reset shadow
    ctx.shadowBlur = 0;

    // Export as PNG
    await new Promise<void>((resolve, reject) => {
      canvas.toBlob((blob) => {
        if (!blob) {
          reject(new Error("Canvas export failed"));
          return;
        }
        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.href = url;
        link.download = `${d.certCode}.png`;
        link.click();
        URL.revokeObjectURL(url);
        resolve();
      }, "image/png");
    });
  }

  async function handleDownload() {
    if (!isReady) return;
    setDl(true);
    try {
      if (cert.autoGenerated && cert.autoInjectData) {
        // Auto-generated: render via canvas overlay onto master template
        await downloadAutoGenerated(cert.autoInjectData);
        toast.success("Certificate downloaded!");
      } else if (cert.certificate) {
        // VIP custom: direct blob download
        const link = document.createElement("a");
        link.href = cert.certificate.getDirectURL();
        link.download = `Certificate-${cert.certCode}`;
        link.target = "_blank";
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        toast.success("Certificate downloaded!");
      } else {
        // Certificate not ready — data not populated yet
        toast.error("Certificate not ready yet, please try again later.");
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Download failed.";
      toast.error(
        msg === "Template not configured — contact admin"
          ? msg
          : "Download failed. Please try again.",
      );
    } finally {
      setDl(false);
    }
  }
  return (
    <div
      className="rounded-xl border border-border p-4 space-y-3 hover:border-primary/30 transition-all"
      style={{
        background:
          "linear-gradient(145deg, oklch(0.155 0.03 265 / 0.8) 0%, oklch(0.14 0.025 260 / 0.8) 100%)",
      }}
      data-ocid="certificate-card"
    >
      <div className="flex items-start justify-between gap-3 flex-wrap">
        <div className="flex items-center gap-2 flex-wrap min-w-0">
          <p className="font-semibold text-foreground truncate">
            {cert.fullName}
          </p>
          {cert.status === "approved" && <GoldenTickBadge show size="sm" />}
        </div>
        <CertStatusBadge status={cert.status} />
      </div>
      <div className="flex items-center gap-3 text-xs text-muted-foreground flex-wrap">
        <span className="font-mono">ID: {cert.certCode}</span>
        <span>Applied: {formatDate(cert.createdAt)}</span>
        {cert.state && (
          <span>
            {cert.state}, {cert.country}
          </span>
        )}
      </div>
      {cert.status === "rejected" && cert.rejectionReason && (
        <div
          className="flex items-start gap-2 rounded-lg px-3 py-2 border border-rose-500/20"
          style={{ background: "oklch(0.62 0.22 22 / 0.06)" }}
          data-ocid="rejection-reason"
        >
          <AlertCircle className="w-3.5 h-3.5 text-rose-400 shrink-0 mt-0.5" />
          <p className="text-xs text-rose-400">
            <span className="font-semibold">Reason:</span>{" "}
            {cert.rejectionReason}
          </p>
        </div>
      )}
      {cert.status === "approved" ? (
        <Button
          size="sm"
          className="gap-1.5 h-8 text-xs"
          onClick={handleDownload}
          disabled={dl}
          data-ocid="download-cert-btn"
        >
          {dl ? (
            <Loader2 className="w-3.5 h-3.5 animate-spin" />
          ) : (
            <Download className="w-3.5 h-3.5" />
          )}
          Download Certificate
        </Button>
      ) : (
        <Button
          size="sm"
          variant="outline"
          className="gap-1.5 h-8 text-xs opacity-50"
          disabled
        >
          <Download className="w-3.5 h-3.5" />
          {cert.status === "pending" ? "Pending Review" : "Not Available"}
        </Button>
      )}
    </div>
  );
}

// ---- Certificate History ----
function CertHistory() {
  const { actor, isReady } = useBackend();
  const { data: certs = [], isLoading } = useQuery<CertificateRequestPublic[]>({
    queryKey: ["my-certificates"],
    queryFn: async () => {
      if (!actor) return [];
      try {
        const a = actor as unknown as Record<string, unknown>;
        if (typeof a.getMyCertificates === "function")
          return await (
            a.getMyCertificates as () => Promise<CertificateRequestPublic[]>
          )();
        return [];
      } catch {
        return [];
      }
    },
    enabled: isReady,
    refetchInterval: 30_000,
  });
  return (
    <div className="card-elevated rounded-xl overflow-hidden">
      <div className="px-5 py-4 border-b border-border flex items-center gap-3 bg-gradient-to-r from-muted/20 to-transparent">
        <div
          className="stat-icon-bg w-8 h-8 shrink-0"
          style={{
            background:
              "linear-gradient(135deg, oklch(0.72 0.22 68 / 0.25) 0%, oklch(0.72 0.22 68 / 0.12) 100%)",
          }}
        >
          <Award className="w-4 h-4 text-amber-400" />
        </div>
        <div>
          <h2 className="font-display font-semibold text-foreground">
            Certificate History
          </h2>
          <p className="text-xs text-muted-foreground">
            All requests & statuses
          </p>
        </div>
        {certs.length > 0 && (
          <span className="text-xs bg-amber-500/10 border border-amber-500/20 text-amber-400 px-2.5 py-1 rounded-full font-mono ml-auto">
            {certs.length}
          </span>
        )}
      </div>
      {isLoading ? (
        <div className="p-4 space-y-3">
          {[0, 1].map((i) => (
            <Skeleton key={i} className="h-24 rounded-xl" />
          ))}
        </div>
      ) : certs.length === 0 ? (
        <div className="empty-state py-12" data-ocid="certs-empty">
          <div className="empty-state-icon mx-auto mb-3 w-14 h-14">
            <Award className="w-7 h-7" />
          </div>
          <p className="font-semibold text-foreground mb-1">
            No certificates yet
          </p>
          <p className="text-sm text-muted-foreground max-w-xs">
            Submit your first request above to get your verified trader
            certificate.
          </p>
        </div>
      ) : (
        <div className="p-4 space-y-3">
          {certs.map((c) => (
            <CertificateCard key={String(c.id)} cert={c} />
          ))}
        </div>
      )}
    </div>
  );
}

// ---- UPI Card ----
function UpiCard({ config }: { config: UpiConfigPublic }) {
  const [copied, setCopied] = useState(false);
  const qrUrl = config.qrCodeBlob?.getDirectURL() ?? DEFAULT_QR_URL;
  const upiId = config.upiId?.trim() ? config.upiId : DEFAULT_UPI_ID;
  function copyUpi() {
    navigator.clipboard.writeText(upiId).then(() => {
      setCopied(true);
      toast.success("Copied!");
      setTimeout(() => setCopied(false), 2500);
    });
  }
  return (
    <div
      className="rounded-xl p-5 border border-border/50 space-y-4"
      style={{
        background:
          "linear-gradient(145deg, oklch(0.16 0.04 265 / 0.95) 0%, oklch(0.14 0.03 260 / 0.95) 100%)",
      }}
    >
      <div className="flex items-center justify-between">
        <div>
          <h3 className="font-display font-bold text-base text-foreground">
            Pay Certificate Fee
          </h3>
          <p className="text-xs text-muted-foreground mt-0.5">
            Scan QR or copy UPI ID
          </p>
        </div>
        <div className="text-right">
          <p className="text-[10px] text-muted-foreground uppercase tracking-wider">
            Amount
          </p>
          <p className="font-display font-bold text-3xl text-amber-400 tabular-nums leading-none">
            ₹99
          </p>
          <p className="text-[10px] text-muted-foreground mt-0.5">
            one-time fee
          </p>
        </div>
      </div>
      <div className="flex gap-4 items-start">
        <div
          className="rounded-xl p-2.5 shrink-0"
          style={{
            background: "oklch(0.96 0 0)",
            border: "3px solid oklch(0.98 0 0 / 0.9)",
          }}
        >
          <img
            src={qrUrl}
            alt="UPI QR"
            className="w-24 h-24 object-contain rounded-lg"
          />
        </div>
        <div className="flex-1 min-w-0 space-y-2">
          <div
            className={`rounded-lg px-3 py-2.5 flex items-center justify-between gap-2 border transition-all duration-300 ${copied ? "border-emerald-500/40 bg-emerald-500/6" : "border-border/60 bg-muted/30"}`}
          >
            <div className="min-w-0">
              <p className="text-[10px] text-muted-foreground uppercase tracking-wider mb-0.5">
                UPI ID
              </p>
              <p className="font-mono text-xs font-bold text-foreground truncate">
                {upiId}
              </p>
            </div>
            <Button
              variant="outline"
              size="sm"
              className={`shrink-0 gap-1 h-7 text-xs ${copied ? "border-emerald-500/50 text-emerald-400" : ""}`}
              onClick={copyUpi}
              type="button"
            >
              {copied ? (
                <CheckCircle2 className="w-3 h-3" />
              ) : (
                <Copy className="w-3 h-3" />
              )}
              {copied ? "Copied" : "Copy"}
            </Button>
          </div>
          <div
            className="flex items-start gap-1.5 rounded-lg px-3 py-2 border border-amber-500/20"
            style={{ background: "oklch(0.72 0.22 68 / 0.06)" }}
          >
            <AlertCircle className="w-3.5 h-3.5 text-amber-400 shrink-0 mt-0.5" />
            <p className="text-xs text-amber-400/90">
              Pay exactly <strong>₹99</strong> and upload screenshot with UTR
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

// ---- Main Page ----
export default function GetCertificate() {
  const { actor, isReady, ensureUserRole } = useBackend();
  const { hasCertificate } = useCertificateStatus();
  const queryClient = useQueryClient();

  const [fullName, setFullName] = useState("");
  const [state, setState] = useState("");
  const [country, setCountry] = useState("India");
  const [email, setEmail] = useState("");
  const [experience, setExperience] = useState("");
  const [ss1, setSs1] = useState<File | null>(null);
  const [ss2, setSs2] = useState<File | null>(null);
  const [payss, setPayss] = useState<File | null>(null);
  const [utr, setUtr] = useState("");
  const [utrErr, setUtrErr] = useState("");
  const [done, setDone] = useState(false);

  const { data: upiConfig, isLoading: upiLoading } = useQuery<UpiConfigPublic>({
    queryKey: ["upi-config"],
    queryFn: async () => {
      if (!actor) throw new Error("Not ready");
      return actor.getUpiConfig();
    },
    enabled: isReady,
  });

  const toBlob = useCallback(
    async (f: File) =>
      ExternalBlob.fromBytes(new Uint8Array(await f.arrayBuffer())),
    [],
  );

  const submitMut = useMutation({
    mutationFn: async () => {
      if (!actor) throw new Error("Not ready");
      await ensureUserRole();
      if (!ss1) throw new Error("Trade screenshot required");
      if (!payss) throw new Error("Payment screenshot required");
      if (!utr.trim() || utr.trim().length < 8)
        throw new Error("Valid UTR required");
      const a = actor as unknown as Record<string, unknown>;
      if (typeof a.submitCertificateRequest !== "function")
        throw new Error("Feature unavailable");
      return await (
        a.submitCertificateRequest as (
          ...args: unknown[]
        ) => Promise<CertificateRequestPublic>
      )(
        fullName.trim(),
        state.trim(),
        country.trim(),
        email.trim() || null,
        experience || null,
        await toBlob(ss1),
        ss2 ? await toBlob(ss2) : null,
        await toBlob(payss),
        utr.trim(),
      );
    },
    onSuccess: () => {
      setDone(true);
      setFullName("");
      setState("");
      setCountry("India");
      setEmail("");
      setExperience("");
      setSs1(null);
      setSs2(null);
      setPayss(null);
      setUtr("");
      setUtrErr("");
      queryClient.invalidateQueries({ queryKey: ["my-certificates"] });
      queryClient.invalidateQueries({ queryKey: ["hasCertificate"] });
      toast.success("Request submitted! Pending review.");
    },
    onError: (e) =>
      toast.error("Submission failed", {
        description: e instanceof Error ? e.message : String(e),
      }),
  });

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!fullName.trim()) {
      toast.error("Full name is required");
      return;
    }
    if (!state.trim()) {
      toast.error("State is required");
      return;
    }
    if (!country.trim()) {
      toast.error("Country is required");
      return;
    }
    if (!ss1) {
      toast.error("Trade screenshot required");
      return;
    }
    if (!payss) {
      toast.error("Payment screenshot required");
      return;
    }
    if (!utr.trim() || utr.trim().length < 8) {
      setUtrErr("Valid UTR required (min 8 chars)");
      return;
    }
    submitMut.mutate();
  }

  return (
    <div className="p-4 sm:p-6 space-y-6 max-w-4xl">
      {/* Header */}
      <div>
        <h1 className="text-heading-1 text-2xl flex items-center gap-2.5">
          <div
            className="stat-icon-bg w-9 h-9 shrink-0"
            style={{
              background:
                "linear-gradient(135deg, oklch(0.72 0.22 68 / 0.28) 0%, oklch(0.72 0.22 68 / 0.15) 100%)",
            }}
          >
            <Award className="w-4 h-4 text-amber-400" />
          </div>
          Get Certificate
          {hasCertificate && <GoldenTickBadge show size="md" />}
        </h1>
        <p className="text-sm text-muted-foreground mt-1 ml-11">
          Submit profitable trades and receive a verified trader certificate
          with a golden tick badge
        </p>
      </div>

      {/* Trust banner */}
      <div
        className="rounded-xl border border-amber-500/20 px-5 py-4 flex items-center gap-4"
        style={{ background: "oklch(0.72 0.22 68 / 0.06)" }}
      >
        <Star className="w-5 h-5 text-amber-400 shrink-0" />
        <div>
          <p className="text-sm font-semibold text-foreground">
            Certified Trader Badge 🟡
          </p>
          <p className="text-xs text-muted-foreground mt-0.5">
            Upon approval, golden tick appears on your profile everywhere your
            username shows.
          </p>
        </div>
      </div>

      {/* Success state */}
      {done && (
        <div
          className="flex items-start gap-3 rounded-xl border border-emerald-500/25 px-5 py-4"
          style={{ background: "oklch(0.65 0.25 142 / 0.06)" }}
          data-ocid="cert-submitted-banner"
        >
          <CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0 mt-0.5" />
          <div>
            <p className="text-sm font-semibold text-emerald-400">
              Request submitted! Pending review.
            </p>
            <p className="text-xs text-emerald-400/80 mt-0.5">
              Admin will verify your application. Check the history below for
              updates.
            </p>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Form */}
        <form
          onSubmit={handleSubmit}
          className="rounded-2xl border border-border/50 p-6 space-y-5"
          style={{
            background:
              "linear-gradient(145deg, oklch(0.155 0.03 265 / 0.9) 0%, oklch(0.14 0.025 260 / 0.9) 100%)",
          }}
        >
          <div>
            <h2 className="font-display font-bold text-lg text-foreground">
              Certificate Application
            </h2>
            <p className="text-xs text-muted-foreground mt-1">
              Fill your details and upload trade proof
            </p>
          </div>

          <div className="space-y-3">
            <p className="text-[10px] font-semibold text-muted-foreground/60 uppercase tracking-widest">
              Personal Information
            </p>
            <div className="space-y-1.5">
              <Label
                htmlFor="cert-fullname"
                className="text-sm font-semibold text-foreground"
              >
                Full Name <span className="text-destructive">*</span>
              </Label>
              <Input
                id="cert-fullname"
                placeholder="As it will appear on certificate"
                value={fullName}
                onChange={(e) => setFullName(e.target.value)}
                className="h-11 input-premium"
                data-ocid="cert-fullname-input"
                required
              />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <Label
                  htmlFor="cert-state"
                  className="text-sm font-semibold text-foreground"
                >
                  State <span className="text-destructive">*</span>
                </Label>
                <Input
                  id="cert-state"
                  placeholder="e.g. Maharashtra"
                  value={state}
                  onChange={(e) => setState(e.target.value)}
                  className="h-11 input-premium"
                  data-ocid="cert-state-input"
                  required
                />
              </div>
              <div className="space-y-1.5">
                <Label
                  htmlFor="cert-country"
                  className="text-sm font-semibold text-foreground"
                >
                  Country <span className="text-destructive">*</span>
                </Label>
                <Input
                  id="cert-country"
                  placeholder="e.g. India"
                  value={country}
                  onChange={(e) => setCountry(e.target.value)}
                  className="h-11 input-premium"
                  data-ocid="cert-country-input"
                  required
                />
              </div>
            </div>
            <div className="space-y-1.5">
              <Label
                htmlFor="cert-email"
                className="text-sm font-semibold text-foreground flex items-center gap-1.5"
              >
                Email{" "}
                <span className="text-xs font-normal text-muted-foreground">
                  (optional)
                </span>
              </Label>
              <Input
                id="cert-email"
                type="email"
                placeholder="For certificate delivery"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="h-11 input-premium"
                data-ocid="cert-email-input"
              />
            </div>
            <div className="space-y-1.5">
              <Label className="text-sm font-semibold text-foreground flex items-center gap-1.5">
                Experience{" "}
                <span className="text-xs font-normal text-muted-foreground">
                  (optional)
                </span>
              </Label>
              <Select value={experience} onValueChange={setExperience}>
                <SelectTrigger
                  className="h-11 input-premium"
                  data-ocid="cert-experience-select"
                >
                  <SelectValue placeholder="Select level" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Beginner">Beginner</SelectItem>
                  <SelectItem value="Intermediate">Intermediate</SelectItem>
                  <SelectItem value="Advanced">Advanced</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="space-y-2">
            <p className="text-[10px] font-semibold text-muted-foreground/60 uppercase tracking-widest">
              Trade Proof
            </p>
            <DropZone
              file={ss1}
              onFile={setSs1}
              label="Trade Screenshot 1"
              required
            />
            <DropZone
              file={ss2}
              onFile={setSs2}
              label="Trade Screenshot 2 (optional)"
            />
          </div>

          <div className="space-y-2">
            <p className="text-[10px] font-semibold text-muted-foreground/60 uppercase tracking-widest">
              Payment Proof (₹99)
            </p>
            <DropZone
              file={payss}
              onFile={setPayss}
              label="Payment Screenshot"
              required
            />
            <div className="space-y-1.5">
              <Label
                htmlFor="cert-utr"
                className="text-sm font-semibold text-foreground flex items-center gap-1.5"
              >
                <Hash className="w-3.5 h-3.5 text-muted-foreground" />
                UTR / Reference Number{" "}
                <span className="text-destructive">*</span>
              </Label>
              <Input
                id="cert-utr"
                placeholder="e.g. 401234567890"
                value={utr}
                onChange={(e) => {
                  setUtr(e.target.value);
                  setUtrErr("");
                }}
                onBlur={() => {
                  if (!utr.trim() || utr.trim().length < 8)
                    setUtrErr("Min 8 chars required");
                }}
                className={`h-11 input-premium font-mono ${utrErr ? "input-invalid" : ""}`}
                data-ocid="cert-utr-input"
              />
              {utrErr && <p className="text-xs text-destructive">⚠ {utrErr}</p>}
            </div>
          </div>

          <Button
            type="submit"
            className="w-full h-12 font-semibold text-base gap-2 shadow-elevated"
            disabled={submitMut.isPending}
            data-ocid="cert-submit-btn"
          >
            {submitMut.isPending ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" /> Submitting…
              </>
            ) : (
              <>
                <Upload className="w-4 h-4" /> Submit Application — ₹99
              </>
            )}
          </Button>
        </form>

        {/* UPI + how it works */}
        <div className="space-y-4">
          {upiLoading ? (
            <div className="rounded-xl p-5 border border-border/50 space-y-3 bg-card/50">
              <Skeleton className="h-6 w-40" />
              <Skeleton className="h-36 rounded-xl" />
            </div>
          ) : upiConfig ? (
            <UpiCard config={upiConfig} />
          ) : (
            <div className="rounded-xl p-5 border border-border/50 text-sm text-muted-foreground text-center bg-card/50">
              UPI config unavailable.
            </div>
          )}

          <div
            className="rounded-xl border border-border/40 p-5 space-y-3"
            style={{ background: "oklch(0.155 0.03 265 / 0.5)" }}
          >
            <p className="text-xs font-semibold text-muted-foreground uppercase tracking-widest">
              How it works
            </p>
            {[
              "Fill form with trading details",
              "Upload 1–2 profitable trade screenshots",
              "Pay ₹99 via UPI and upload proof",
              "Admin verifies → Certificate + Golden Tick!",
            ].map((t, i) => (
              <div key={t} className="flex items-center gap-3">
                <div className="w-6 h-6 rounded-full bg-primary/15 border border-primary/30 flex items-center justify-center shrink-0">
                  <span className="text-xs font-bold text-primary">
                    {i + 1}
                  </span>
                </div>
                <p className="text-xs text-muted-foreground">{t}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Certificate History */}
      <CertHistory />
    </div>
  );
}
