import { CertificateStatus } from "../backend";
import type {
  PaymentId,
  PaymentPublic,
  Signal,
  SignalId,
  SignalType,
  SubscriptionPublic,
  Timestamp,
  TradeStatus,
  UpiConfigPublic,
  UserId,
} from "../backend";

// PaymentStatus shares the same values as CertificateStatus (pending/approved/rejected)
// Re-export CertificateStatus both by its original name and as PaymentStatus
export { CertificateStatus };
export { CertificateStatus as PaymentStatus };

export type {
  Signal,
  SignalType,
  TradeStatus,
  PaymentPublic,
  SubscriptionPublic,
  UpiConfigPublic,
  UserId,
  SignalId,
  PaymentId,
  Timestamp,
};

export interface AuthUser {
  principal: string;
  isAdmin: boolean;
}

export interface ToastMessage {
  id: string;
  type: "success" | "error" | "info" | "warning";
  title: string;
  description?: string;
}

export interface NavItem {
  label: string;
  href: string;
  icon: string;
}

export interface SignalFormData {
  pair: string;
  signalType: SignalType;
  entryPrice: number;
  stopLoss: number;
  takeProfit: number;
  confidence: number;
  screenshotKey?: string;
  tradeStatus?: TradeStatus;
}

// Certificate types — CertificateStatus is imported from backend above

export interface AutoInjectData {
  fullName: string;
  issueDate: string;
  certCode: string;
}

export interface CertificateRequestPublic {
  id: bigint;
  userId: string;
  fullName: string;
  state: string;
  country: string;
  email?: string;
  experience?: string;
  paymentAmount: number;
  utrNumber: string;
  status: CertificateStatus;
  rejectionReason?: string;
  certCode: string;
  certificate?: {
    getBytes: () => Promise<Uint8Array>;
    getDirectURL: () => string;
  };
  autoGenerated: boolean;
  autoInjectData?: AutoInjectData;
  createdAt: bigint;
  updatedAt: bigint;
  screenshot1Key?: string;
  screenshot2Key?: string;
  paymentScreenshotKey?: string;
}

export interface MasterTemplate {
  blob?: {
    getBytes: () => Promise<Uint8Array>;
    getDirectURL: () => string;
  };
  updatedAt: bigint;
}
