/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppSettings {
  'walletNetwork' : string,
  'walletAddress' : string,
  'currency' : Currency,
  'upiId' : string,
  'paymentType' : PaymentType,
  'heroContent' : HeroContent,
  'footerContent' : FooterContent,
  'whyChoose' : WhyChooseSection,
  'buttonLabels' : ButtonLabels,
}
export interface ButtonLabels {
  'whatsappButtonText' : string,
  'supportButtonText' : string,
}
export interface ContactDetails {
  'whatsapp' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
  'socialMedia' : Array<SocialLink>,
}
export interface CryptoListing {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'price' : number,
  'symbol' : string,
}
export interface CryptoOrderPublic {
  'id' : bigint,
  'status' : OrderStatus,
  'completedAt' : [] | [bigint],
  'cryptoType' : string,
  'cryptoSymbol' : string,
  'userId' : Principal,
  'screenshotUrl' : string,
  'createdAt' : bigint,
  'network' : string,
  'walletAddress' : string,
  'reviewComment' : string,
  'reviewStatus' : ReviewStatus,
}
export type Currency = { 'INR' : null } |
  { 'USD' : null };
export interface FooterContent {
  'links' : Array<FooterLink>,
  'copyright' : string,
}
export interface FooterLink { 'url' : string, 'text' : string }
export interface HeroContent {
  'headline' : string,
  'ctaText' : string,
  'ctaSubtext' : string,
  'subtitle' : string,
}
export interface Lead {
  'id' : LeadId,
  'fullName' : string,
  'timestamp' : bigint,
  'contactNumber' : string,
}
export type LeadId = bigint;
export type OrderStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null };
export type PaymentType = { 'UPI' : null } |
  { 'CryptoWallet' : null };
export type ReviewStatus = { 'trusted' : null } |
  { 'none' : null } |
  { 'notTrusted' : null };
export interface Service {
  'id' : ServiceId,
  'title' : string,
  'sortOrder' : bigint,
  'description' : string,
  'iconName' : string,
}
export type ServiceId = bigint;
export interface SocialLink { 'url' : string, 'platform' : string }
export interface SubmitOrderRequest {
  'cryptoType' : string,
  'cryptoSymbol' : string,
  'screenshotUrl' : string,
  'network' : string,
  'walletAddress' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WhyChooseFeature {
  'title' : string,
  'icon' : string,
  'description' : string,
}
export interface WhyChooseSection {
  'title' : string,
  'features' : Array<WhyChooseFeature>,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addService' : ActorMethod<[string, string, string, bigint], Service>,
  'adminAddCryptoListing' : ActorMethod<
    [string, string, string, number],
    bigint
  >,
  'adminCompleteOrder' : ActorMethod<[bigint], boolean>,
  'adminDeleteCryptoListing' : ActorMethod<[bigint], boolean>,
  'adminListAllCryptoListings' : ActorMethod<[], Array<CryptoListing>>,
  'adminListAllOrders' : ActorMethod<[], Array<CryptoOrderPublic>>,
  'adminListPendingOrders' : ActorMethod<[], Array<CryptoOrderPublic>>,
  'adminRejectOrder' : ActorMethod<[bigint], boolean>,
  'adminUpdateCryptoListing' : ActorMethod<
    [bigint, string, string, string, number, boolean],
    boolean
  >,
  'adminUpdateSettings' : ActorMethod<[AppSettings], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'captureLead' : ActorMethod<[string, string], Lead>,
  'claimAdminRole' : ActorMethod<[string], boolean>,
  'deleteLead' : ActorMethod<[LeadId], boolean>,
  'deleteService' : ActorMethod<[ServiceId], boolean>,
  'getAppSettings' : ActorMethod<[], AppSettings>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactDetails' : ActorMethod<[], [] | [ContactDetails]>,
  'getCryptoListing' : ActorMethod<[bigint], [] | [CryptoListing]>,
  'getLead' : ActorMethod<[LeadId], [] | [Lead]>,
  'getMyOrders' : ActorMethod<[], Array<CryptoOrderPublic>>,
  'getService' : ActorMethod<[ServiceId], [] | [Service]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActiveCryptoListings' : ActorMethod<[], Array<CryptoListing>>,
  'listLeads' : ActorMethod<[], Array<Lead>>,
  'listServices' : ActorMethod<[], Array<Service>>,
  'pollNewlyCompletedOrders' : ActorMethod<[], Array<CryptoOrderPublic>>,
  'selfRegister' : ActorMethod<[], undefined>,
  'setContactDetails' : ActorMethod<
    [string, string, string, string, Array<SocialLink>],
    ContactDetails
  >,
  'submitCryptoOrder' : ActorMethod<[SubmitOrderRequest], bigint>,
  'submitOrderReview' : ActorMethod<[bigint, ReviewStatus, string], boolean>,
  'updateService' : ActorMethod<
    [ServiceId, string, string, string, bigint],
    [] | [Service]
  >,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];