/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserId = IDL.Principal;
export const TradeStatus = IDL.Variant({
  'pending' : IDL.Null,
  'success' : IDL.Null,
  'failed' : IDL.Null,
});
export const SignalType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const SignalInput = IDL.Record({
  'takeProfit' : IDL.Float64,
  'screenshotKey' : IDL.Opt(IDL.Text),
  'pair' : IDL.Text,
  'stopLoss' : IDL.Float64,
  'entryPrice' : IDL.Float64,
  'confidence' : IDL.Nat,
  'tradeStatus' : IDL.Opt(TradeStatus),
  'signalType' : SignalType,
});
export const SignalId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Signal = IDL.Record({
  'id' : SignalId,
  'proofKey' : IDL.Opt(IDL.Text),
  'takeProfit' : IDL.Float64,
  'screenshotKey' : IDL.Opt(IDL.Text),
  'pair' : IDL.Text,
  'isActive' : IDL.Bool,
  'stopLoss' : IDL.Float64,
  'timestamp' : Timestamp,
  'entryPrice' : IDL.Float64,
  'confidence' : IDL.Nat,
  'tradeStatus' : TradeStatus,
  'signalType' : SignalType,
});
export const CertificateId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CertificateStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const AutoInjectData = IDL.Record({
  'issueDate' : IDL.Text,
  'certCode' : IDL.Text,
  'fullName' : IDL.Text,
});
export const CertificateRequestPublic = IDL.Record({
  'id' : CertificateId,
  'status' : CertificateStatus,
  'paymentScreenshot' : ExternalBlob,
  'certCode' : IDL.Text,
  'certificate' : IDL.Opt(ExternalBlob),
  'country' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'fullName' : IDL.Text,
  'autoInjectData' : IDL.Opt(AutoInjectData),
  'email' : IDL.Opt(IDL.Text),
  'autoGenerated' : IDL.Bool,
  'experience' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'state' : IDL.Text,
  'screenshot1' : ExternalBlob,
  'screenshot2' : IDL.Opt(ExternalBlob),
  'utrNumber' : IDL.Text,
  'paymentAmount' : IDL.Nat,
});
export const PaymentId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PaymentPublic = IDL.Record({
  'id' : PaymentId,
  'status' : PaymentStatus,
  'userId' : UserId,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'timestamp' : Timestamp,
  'senderName' : IDL.Text,
  'utrNumber' : IDL.Text,
  'screenshotBlob' : ExternalBlob,
});
export const SubscriptionPublic = IDL.Record({
  'expiresAt' : Timestamp,
  'userId' : UserId,
  'isActive' : IDL.Bool,
});
export const TradeStats = IDL.Record({
  'failedSignals' : IDL.Nat,
  'winRate' : IDL.Float64,
  'totalSignals' : IDL.Nat,
  'successSignals' : IDL.Nat,
});
export const UpiConfigPublic = IDL.Record({
  'qrCodeBlob' : IDL.Opt(ExternalBlob),
  'upiId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'activateUserSubscription' : IDL.Func([UserId], [], []),
  'addSignal' : IDL.Func([SignalInput], [Signal], []),
  'approveCertificate' : IDL.Func(
      [CertificateId, IDL.Opt(ExternalBlob)],
      [CertificateRequestPublic],
      [],
    ),
  'approvePayment' : IDL.Func([PaymentId], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkSubscriptionStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'claimAdminRole' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteSignal' : IDL.Func([SignalId], [IDL.Bool], []),
  'getActiveSubscriberCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMasterTemplate' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getMyCertificates' : IDL.Func(
      [],
      [IDL.Vec(CertificateRequestPublic)],
      ['query'],
    ),
  'getMyPayments' : IDL.Func([], [IDL.Vec(PaymentPublic)], ['query']),
  'getMySubscription' : IDL.Func([], [IDL.Opt(SubscriptionPublic)], ['query']),
  'getTradeStats' : IDL.Func([], [TradeStats], ['query']),
  'getUpiConfig' : IDL.Func([], [UpiConfigPublic], ['query']),
  'hasCertificate' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllCertificateRequests' : IDL.Func(
      [],
      [IDL.Vec(CertificateRequestPublic)],
      ['query'],
    ),
  'listAllPayments' : IDL.Func([], [IDL.Vec(PaymentPublic)], ['query']),
  'listPublicSuccessSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
  'listSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
  'markTradeOutcome' : IDL.Func(
      [
        SignalId,
        IDL.Variant({ 'success' : IDL.Null, 'failed' : IDL.Null }),
        IDL.Opt(IDL.Text),
      ],
      [Signal],
      [],
    ),
  'rejectCertificate' : IDL.Func(
      [CertificateId, IDL.Opt(IDL.Text)],
      [CertificateRequestPublic],
      [],
    ),
  'rejectPayment' : IDL.Func([PaymentId, IDL.Text], [IDL.Bool], []),
  'selfRegister' : IDL.Func([], [], []),
  'submitCertificateRequest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        ExternalBlob,
        IDL.Opt(ExternalBlob),
        ExternalBlob,
        IDL.Text,
      ],
      [CertificateRequestPublic],
      [],
    ),
  'submitPayment' : IDL.Func(
      [ExternalBlob, IDL.Text, IDL.Text],
      [PaymentPublic],
      [],
    ),
  'updateMasterTemplate' : IDL.Func([ExternalBlob], [], []),
  'updateQrCode' : IDL.Func([ExternalBlob], [], []),
  'updateSignal' : IDL.Func([SignalId, SignalInput], [IDL.Bool], []),
  'updateUpiId' : IDL.Func([IDL.Text], [], []),
  'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'verifyCertificate' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CertificateRequestPublic)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserId = IDL.Principal;
  const TradeStatus = IDL.Variant({
    'pending' : IDL.Null,
    'success' : IDL.Null,
    'failed' : IDL.Null,
  });
  const SignalType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const SignalInput = IDL.Record({
    'takeProfit' : IDL.Float64,
    'screenshotKey' : IDL.Opt(IDL.Text),
    'pair' : IDL.Text,
    'stopLoss' : IDL.Float64,
    'entryPrice' : IDL.Float64,
    'confidence' : IDL.Nat,
    'tradeStatus' : IDL.Opt(TradeStatus),
    'signalType' : SignalType,
  });
  const SignalId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Signal = IDL.Record({
    'id' : SignalId,
    'proofKey' : IDL.Opt(IDL.Text),
    'takeProfit' : IDL.Float64,
    'screenshotKey' : IDL.Opt(IDL.Text),
    'pair' : IDL.Text,
    'isActive' : IDL.Bool,
    'stopLoss' : IDL.Float64,
    'timestamp' : Timestamp,
    'entryPrice' : IDL.Float64,
    'confidence' : IDL.Nat,
    'tradeStatus' : TradeStatus,
    'signalType' : SignalType,
  });
  const CertificateId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CertificateStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const AutoInjectData = IDL.Record({
    'issueDate' : IDL.Text,
    'certCode' : IDL.Text,
    'fullName' : IDL.Text,
  });
  const CertificateRequestPublic = IDL.Record({
    'id' : CertificateId,
    'status' : CertificateStatus,
    'paymentScreenshot' : ExternalBlob,
    'certCode' : IDL.Text,
    'certificate' : IDL.Opt(ExternalBlob),
    'country' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'fullName' : IDL.Text,
    'autoInjectData' : IDL.Opt(AutoInjectData),
    'email' : IDL.Opt(IDL.Text),
    'autoGenerated' : IDL.Bool,
    'experience' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'state' : IDL.Text,
    'screenshot1' : ExternalBlob,
    'screenshot2' : IDL.Opt(ExternalBlob),
    'utrNumber' : IDL.Text,
    'paymentAmount' : IDL.Nat,
  });
  const PaymentId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PaymentPublic = IDL.Record({
    'id' : PaymentId,
    'status' : PaymentStatus,
    'userId' : UserId,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'timestamp' : Timestamp,
    'senderName' : IDL.Text,
    'utrNumber' : IDL.Text,
    'screenshotBlob' : ExternalBlob,
  });
  const SubscriptionPublic = IDL.Record({
    'expiresAt' : Timestamp,
    'userId' : UserId,
    'isActive' : IDL.Bool,
  });
  const TradeStats = IDL.Record({
    'failedSignals' : IDL.Nat,
    'winRate' : IDL.Float64,
    'totalSignals' : IDL.Nat,
    'successSignals' : IDL.Nat,
  });
  const UpiConfigPublic = IDL.Record({
    'qrCodeBlob' : IDL.Opt(ExternalBlob),
    'upiId' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'activateUserSubscription' : IDL.Func([UserId], [], []),
    'addSignal' : IDL.Func([SignalInput], [Signal], []),
    'approveCertificate' : IDL.Func(
        [CertificateId, IDL.Opt(ExternalBlob)],
        [CertificateRequestPublic],
        [],
      ),
    'approvePayment' : IDL.Func([PaymentId], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkSubscriptionStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'claimAdminRole' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteSignal' : IDL.Func([SignalId], [IDL.Bool], []),
    'getActiveSubscriberCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMasterTemplate' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getMyCertificates' : IDL.Func(
        [],
        [IDL.Vec(CertificateRequestPublic)],
        ['query'],
      ),
    'getMyPayments' : IDL.Func([], [IDL.Vec(PaymentPublic)], ['query']),
    'getMySubscription' : IDL.Func(
        [],
        [IDL.Opt(SubscriptionPublic)],
        ['query'],
      ),
    'getTradeStats' : IDL.Func([], [TradeStats], ['query']),
    'getUpiConfig' : IDL.Func([], [UpiConfigPublic], ['query']),
    'hasCertificate' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllCertificateRequests' : IDL.Func(
        [],
        [IDL.Vec(CertificateRequestPublic)],
        ['query'],
      ),
    'listAllPayments' : IDL.Func([], [IDL.Vec(PaymentPublic)], ['query']),
    'listPublicSuccessSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
    'listSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
    'markTradeOutcome' : IDL.Func(
        [
          SignalId,
          IDL.Variant({ 'success' : IDL.Null, 'failed' : IDL.Null }),
          IDL.Opt(IDL.Text),
        ],
        [Signal],
        [],
      ),
    'rejectCertificate' : IDL.Func(
        [CertificateId, IDL.Opt(IDL.Text)],
        [CertificateRequestPublic],
        [],
      ),
    'rejectPayment' : IDL.Func([PaymentId, IDL.Text], [IDL.Bool], []),
    'selfRegister' : IDL.Func([], [], []),
    'submitCertificateRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          ExternalBlob,
          IDL.Opt(ExternalBlob),
          ExternalBlob,
          IDL.Text,
        ],
        [CertificateRequestPublic],
        [],
      ),
    'submitPayment' : IDL.Func(
        [ExternalBlob, IDL.Text, IDL.Text],
        [PaymentPublic],
        [],
      ),
    'updateMasterTemplate' : IDL.Func([ExternalBlob], [], []),
    'updateQrCode' : IDL.Func([ExternalBlob], [], []),
    'updateSignal' : IDL.Func([SignalId, SignalInput], [IDL.Bool], []),
    'updateUpiId' : IDL.Func([IDL.Text], [], []),
    'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'verifyCertificate' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CertificateRequestPublic)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };