/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AutoInjectData {
  'issueDate' : string,
  'certCode' : string,
  'fullName' : string,
}
export type CertificateId = bigint;
export interface CertificateRequestPublic {
  'id' : CertificateId,
  'status' : CertificateStatus,
  'paymentScreenshot' : ExternalBlob,
  'certCode' : string,
  'certificate' : [] | [ExternalBlob],
  'country' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'rejectionReason' : [] | [string],
  'fullName' : string,
  'autoInjectData' : [] | [AutoInjectData],
  'email' : [] | [string],
  'autoGenerated' : boolean,
  'experience' : [] | [string],
  'updatedAt' : Timestamp,
  'state' : string,
  'screenshot1' : ExternalBlob,
  'screenshot2' : [] | [ExternalBlob],
  'utrNumber' : string,
  'paymentAmount' : bigint,
}
export type CertificateStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ExternalBlob = Uint8Array;
export type PaymentId = bigint;
export interface PaymentPublic {
  'id' : PaymentId,
  'status' : PaymentStatus,
  'userId' : UserId,
  'rejectionReason' : [] | [string],
  'timestamp' : Timestamp,
  'senderName' : string,
  'utrNumber' : string,
  'screenshotBlob' : ExternalBlob,
}
export type PaymentStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Signal {
  'id' : SignalId,
  'proofKey' : [] | [string],
  'takeProfit' : number,
  'screenshotKey' : [] | [string],
  'pair' : string,
  'isActive' : boolean,
  'stopLoss' : number,
  'timestamp' : Timestamp,
  'entryPrice' : number,
  'confidence' : bigint,
  'tradeStatus' : TradeStatus,
  'signalType' : SignalType,
}
export type SignalId = bigint;
export interface SignalInput {
  'takeProfit' : number,
  'screenshotKey' : [] | [string],
  'pair' : string,
  'stopLoss' : number,
  'entryPrice' : number,
  'confidence' : bigint,
  'tradeStatus' : [] | [TradeStatus],
  'signalType' : SignalType,
}
export type SignalType = { 'buy' : null } |
  { 'sell' : null };
export interface SubscriptionPublic {
  'expiresAt' : Timestamp,
  'userId' : UserId,
  'isActive' : boolean,
}
export type Timestamp = bigint;
export interface TradeStats {
  'failedSignals' : bigint,
  'winRate' : number,
  'totalSignals' : bigint,
  'successSignals' : bigint,
}
export type TradeStatus = { 'pending' : null } |
  { 'success' : null } |
  { 'failed' : null };
export interface UpiConfigPublic {
  'qrCodeBlob' : [] | [ExternalBlob],
  'upiId' : string,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'activateUserSubscription' : ActorMethod<[UserId], undefined>,
  'addSignal' : ActorMethod<[SignalInput], Signal>,
  'approveCertificate' : ActorMethod<
    [CertificateId, [] | [ExternalBlob]],
    CertificateRequestPublic
  >,
  'approvePayment' : ActorMethod<[PaymentId], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkSubscriptionStatus' : ActorMethod<[], boolean>,
  'claimAdminRole' : ActorMethod<[string], boolean>,
  'deleteSignal' : ActorMethod<[SignalId], boolean>,
  'getActiveSubscriberCount' : ActorMethod<[], bigint>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMasterTemplate' : ActorMethod<[], [] | [ExternalBlob]>,
  'getMyCertificates' : ActorMethod<[], Array<CertificateRequestPublic>>,
  'getMyPayments' : ActorMethod<[], Array<PaymentPublic>>,
  'getMySubscription' : ActorMethod<[], [] | [SubscriptionPublic]>,
  'getTradeStats' : ActorMethod<[], TradeStats>,
  'getUpiConfig' : ActorMethod<[], UpiConfigPublic>,
  'hasCertificate' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllCertificateRequests' : ActorMethod<
    [],
    Array<CertificateRequestPublic>
  >,
  'listAllPayments' : ActorMethod<[], Array<PaymentPublic>>,
  'listPublicSuccessSignals' : ActorMethod<[], Array<Signal>>,
  'listSignals' : ActorMethod<[], Array<Signal>>,
  'markTradeOutcome' : ActorMethod<
    [SignalId, { 'success' : null } | { 'failed' : null }, [] | [string]],
    Signal
  >,
  'rejectCertificate' : ActorMethod<
    [CertificateId, [] | [string]],
    CertificateRequestPublic
  >,
  'rejectPayment' : ActorMethod<[PaymentId, string], boolean>,
  'selfRegister' : ActorMethod<[], undefined>,
  'submitCertificateRequest' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [string],
      [] | [string],
      ExternalBlob,
      [] | [ExternalBlob],
      ExternalBlob,
      string,
    ],
    CertificateRequestPublic
  >,
  'submitPayment' : ActorMethod<[ExternalBlob, string, string], PaymentPublic>,
  'updateMasterTemplate' : ActorMethod<[ExternalBlob], undefined>,
  'updateQrCode' : ActorMethod<[ExternalBlob], undefined>,
  'updateSignal' : ActorMethod<[SignalId, SignalInput], boolean>,
  'updateUpiId' : ActorMethod<[string], undefined>,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
  'verifyCertificate' : ActorMethod<[string], [] | [CertificateRequestPublic]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];