/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ServiceId = IDL.Nat;
export const Service = IDL.Record({
  'id' : ServiceId,
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'description' : IDL.Text,
  'iconName' : IDL.Text,
});
export const CryptoListing = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ReviewStatus = IDL.Variant({
  'trusted' : IDL.Null,
  'none' : IDL.Null,
  'notTrusted' : IDL.Null,
});
export const CryptoOrderPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'completedAt' : IDL.Opt(IDL.Int),
  'cryptoType' : IDL.Text,
  'cryptoSymbol' : IDL.Text,
  'userId' : IDL.Principal,
  'screenshotUrl' : IDL.Text,
  'createdAt' : IDL.Int,
  'network' : IDL.Text,
  'walletAddress' : IDL.Text,
  'reviewComment' : IDL.Text,
  'reviewStatus' : ReviewStatus,
});
export const Currency = IDL.Variant({ 'INR' : IDL.Null, 'USD' : IDL.Null });
export const PaymentType = IDL.Variant({
  'UPI' : IDL.Null,
  'CryptoWallet' : IDL.Null,
});
export const HeroContent = IDL.Record({
  'headline' : IDL.Text,
  'ctaText' : IDL.Text,
  'ctaSubtext' : IDL.Text,
  'subtitle' : IDL.Text,
});
export const FooterLink = IDL.Record({ 'url' : IDL.Text, 'text' : IDL.Text });
export const FooterContent = IDL.Record({
  'links' : IDL.Vec(FooterLink),
  'copyright' : IDL.Text,
});
export const WhyChooseFeature = IDL.Record({
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
});
export const WhyChooseSection = IDL.Record({
  'title' : IDL.Text,
  'features' : IDL.Vec(WhyChooseFeature),
});
export const ButtonLabels = IDL.Record({
  'whatsappButtonText' : IDL.Text,
  'supportButtonText' : IDL.Text,
});
export const AppSettings = IDL.Record({
  'walletNetwork' : IDL.Text,
  'walletAddress' : IDL.Text,
  'currency' : Currency,
  'upiId' : IDL.Text,
  'paymentType' : PaymentType,
  'heroContent' : HeroContent,
  'footerContent' : FooterContent,
  'whyChoose' : WhyChooseSection,
  'buttonLabels' : ButtonLabels,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LeadId = IDL.Nat;
export const Lead = IDL.Record({
  'id' : LeadId,
  'fullName' : IDL.Text,
  'timestamp' : IDL.Int,
  'contactNumber' : IDL.Text,
});
export const SocialLink = IDL.Record({
  'url' : IDL.Text,
  'platform' : IDL.Text,
});
export const ContactDetails = IDL.Record({
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'socialMedia' : IDL.Vec(SocialLink),
});
export const SubmitOrderRequest = IDL.Record({
  'cryptoType' : IDL.Text,
  'cryptoSymbol' : IDL.Text,
  'screenshotUrl' : IDL.Text,
  'network' : IDL.Text,
  'walletAddress' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Service],
      [],
    ),
  'adminAddCryptoListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'adminCompleteOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'adminDeleteCryptoListing' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'adminListAllCryptoListings' : IDL.Func(
      [],
      [IDL.Vec(CryptoListing)],
      ['query'],
    ),
  'adminListAllOrders' : IDL.Func([], [IDL.Vec(CryptoOrderPublic)], ['query']),
  'adminListPendingOrders' : IDL.Func(
      [],
      [IDL.Vec(CryptoOrderPublic)],
      ['query'],
    ),
  'adminRejectOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'adminUpdateCryptoListing' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'adminUpdateSettings' : IDL.Func([AppSettings], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'captureLead' : IDL.Func([IDL.Text, IDL.Text], [Lead], []),
  'claimAdminRole' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteLead' : IDL.Func([LeadId], [IDL.Bool], []),
  'deleteService' : IDL.Func([ServiceId], [IDL.Bool], []),
  'getAppSettings' : IDL.Func([], [AppSettings], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactDetails' : IDL.Func([], [IDL.Opt(ContactDetails)], ['query']),
  'getCryptoListing' : IDL.Func([IDL.Nat], [IDL.Opt(CryptoListing)], ['query']),
  'getLead' : IDL.Func([LeadId], [IDL.Opt(Lead)], []),
  'getMyOrders' : IDL.Func([], [IDL.Vec(CryptoOrderPublic)], ['query']),
  'getService' : IDL.Func([ServiceId], [IDL.Opt(Service)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActiveCryptoListings' : IDL.Func(
      [],
      [IDL.Vec(CryptoListing)],
      ['query'],
    ),
  'listLeads' : IDL.Func([], [IDL.Vec(Lead)], []),
  'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'pollNewlyCompletedOrders' : IDL.Func(
      [],
      [IDL.Vec(CryptoOrderPublic)],
      ['query'],
    ),
  'selfRegister' : IDL.Func([], [], []),
  'setContactDetails' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(SocialLink)],
      [ContactDetails],
      [],
    ),
  'submitCryptoOrder' : IDL.Func([SubmitOrderRequest], [IDL.Nat], []),
  'submitOrderReview' : IDL.Func(
      [IDL.Nat, ReviewStatus, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateService' : IDL.Func(
      [ServiceId, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Opt(Service)],
      [],
    ),
  'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ServiceId = IDL.Nat;
  const Service = IDL.Record({
    'id' : ServiceId,
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'description' : IDL.Text,
    'iconName' : IDL.Text,
  });
  const CryptoListing = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ReviewStatus = IDL.Variant({
    'trusted' : IDL.Null,
    'none' : IDL.Null,
    'notTrusted' : IDL.Null,
  });
  const CryptoOrderPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'completedAt' : IDL.Opt(IDL.Int),
    'cryptoType' : IDL.Text,
    'cryptoSymbol' : IDL.Text,
    'userId' : IDL.Principal,
    'screenshotUrl' : IDL.Text,
    'createdAt' : IDL.Int,
    'network' : IDL.Text,
    'walletAddress' : IDL.Text,
    'reviewComment' : IDL.Text,
    'reviewStatus' : ReviewStatus,
  });
  const Currency = IDL.Variant({ 'INR' : IDL.Null, 'USD' : IDL.Null });
  const PaymentType = IDL.Variant({
    'UPI' : IDL.Null,
    'CryptoWallet' : IDL.Null,
  });
  const HeroContent = IDL.Record({
    'headline' : IDL.Text,
    'ctaText' : IDL.Text,
    'ctaSubtext' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  const FooterLink = IDL.Record({ 'url' : IDL.Text, 'text' : IDL.Text });
  const FooterContent = IDL.Record({
    'links' : IDL.Vec(FooterLink),
    'copyright' : IDL.Text,
  });
  const WhyChooseFeature = IDL.Record({
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
  });
  const WhyChooseSection = IDL.Record({
    'title' : IDL.Text,
    'features' : IDL.Vec(WhyChooseFeature),
  });
  const ButtonLabels = IDL.Record({
    'whatsappButtonText' : IDL.Text,
    'supportButtonText' : IDL.Text,
  });
  const AppSettings = IDL.Record({
    'walletNetwork' : IDL.Text,
    'walletAddress' : IDL.Text,
    'currency' : Currency,
    'upiId' : IDL.Text,
    'paymentType' : PaymentType,
    'heroContent' : HeroContent,
    'footerContent' : FooterContent,
    'whyChoose' : WhyChooseSection,
    'buttonLabels' : ButtonLabels,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LeadId = IDL.Nat;
  const Lead = IDL.Record({
    'id' : LeadId,
    'fullName' : IDL.Text,
    'timestamp' : IDL.Int,
    'contactNumber' : IDL.Text,
  });
  const SocialLink = IDL.Record({ 'url' : IDL.Text, 'platform' : IDL.Text });
  const ContactDetails = IDL.Record({
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'socialMedia' : IDL.Vec(SocialLink),
  });
  const SubmitOrderRequest = IDL.Record({
    'cryptoType' : IDL.Text,
    'cryptoSymbol' : IDL.Text,
    'screenshotUrl' : IDL.Text,
    'network' : IDL.Text,
    'walletAddress' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Service],
        [],
      ),
    'adminAddCryptoListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'adminCompleteOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'adminDeleteCryptoListing' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'adminListAllCryptoListings' : IDL.Func(
        [],
        [IDL.Vec(CryptoListing)],
        ['query'],
      ),
    'adminListAllOrders' : IDL.Func(
        [],
        [IDL.Vec(CryptoOrderPublic)],
        ['query'],
      ),
    'adminListPendingOrders' : IDL.Func(
        [],
        [IDL.Vec(CryptoOrderPublic)],
        ['query'],
      ),
    'adminRejectOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'adminUpdateCryptoListing' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'adminUpdateSettings' : IDL.Func([AppSettings], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'captureLead' : IDL.Func([IDL.Text, IDL.Text], [Lead], []),
    'claimAdminRole' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteLead' : IDL.Func([LeadId], [IDL.Bool], []),
    'deleteService' : IDL.Func([ServiceId], [IDL.Bool], []),
    'getAppSettings' : IDL.Func([], [AppSettings], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactDetails' : IDL.Func([], [IDL.Opt(ContactDetails)], ['query']),
    'getCryptoListing' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CryptoListing)],
        ['query'],
      ),
    'getLead' : IDL.Func([LeadId], [IDL.Opt(Lead)], []),
    'getMyOrders' : IDL.Func([], [IDL.Vec(CryptoOrderPublic)], ['query']),
    'getService' : IDL.Func([ServiceId], [IDL.Opt(Service)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActiveCryptoListings' : IDL.Func(
        [],
        [IDL.Vec(CryptoListing)],
        ['query'],
      ),
    'listLeads' : IDL.Func([], [IDL.Vec(Lead)], []),
    'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'pollNewlyCompletedOrders' : IDL.Func(
        [],
        [IDL.Vec(CryptoOrderPublic)],
        ['query'],
      ),
    'selfRegister' : IDL.Func([], [], []),
    'setContactDetails' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(SocialLink)],
        [ContactDetails],
        [],
      ),
    'submitCryptoOrder' : IDL.Func([SubmitOrderRequest], [IDL.Nat], []),
    'submitOrderReview' : IDL.Func(
        [IDL.Nat, ReviewStatus, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateService' : IDL.Func(
        [ServiceId, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Opt(Service)],
        [],
      ),
    'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };