/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Signal {
    id: SignalId;
    proofKey?: string;
    takeProfit: number;
    screenshotKey?: string;
    pair: string;
    isActive: boolean;
    stopLoss: number;
    timestamp: Timestamp;
    entryPrice: number;
    confidence: bigint;
    tradeStatus: TradeStatus;
    signalType: SignalType;
}
export interface AutoInjectData {
    issueDate: string;
    certCode: string;
    fullName: string;
}
export type Timestamp = bigint;
export type SignalId = bigint;
export interface SignalInput {
    takeProfit: number;
    screenshotKey?: string;
    pair: string;
    stopLoss: number;
    entryPrice: number;
    confidence: bigint;
    tradeStatus?: TradeStatus;
    signalType: SignalType;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PaymentPublic {
    id: PaymentId;
    status: PaymentStatus;
    userId: UserId;
    rejectionReason?: string;
    timestamp: Timestamp;
    senderName: string;
    utrNumber: string;
    screenshotBlob: ExternalBlob;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UpiConfigPublic {
    qrCodeBlob?: ExternalBlob;
    upiId: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface CertificateRequestPublic {
    id: CertificateId;
    status: CertificateStatus;
    paymentScreenshot: ExternalBlob;
    certCode: string;
    certificate?: ExternalBlob;
    country: string;
    userId: UserId;
    createdAt: Timestamp;
    rejectionReason?: string;
    fullName: string;
    autoInjectData?: AutoInjectData;
    email?: string;
    autoGenerated: boolean;
    experience?: string;
    updatedAt: Timestamp;
    state: string;
    screenshot1: ExternalBlob;
    screenshot2?: ExternalBlob;
    utrNumber: string;
    paymentAmount: bigint;
}
export type UserId = Principal;
export interface TradeStats {
    failedSignals: bigint;
    winRate: number;
    totalSignals: bigint;
    successSignals: bigint;
}
export type CertificateId = bigint;
export type PaymentId = bigint;
export interface SubscriptionPublic {
    expiresAt: Timestamp;
    userId: UserId;
    isActive: boolean;
}
export enum CertificateStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum SignalType {
    buy = "buy",
    sell = "sell"
}
export enum TradeStatus {
    pending = "pending",
    success = "success",
    failed = "failed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_success_failed {
    success = "success",
    failed = "failed"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    activateUserSubscription(userId: UserId): Promise<void>;
    addSignal(input: SignalInput): Promise<Signal>;
    approveCertificate(certId: CertificateId, customCertificate: ExternalBlob | null): Promise<CertificateRequestPublic>;
    approvePayment(id: PaymentId): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkSubscriptionStatus(): Promise<boolean>;
    claimAdminRole(password: string): Promise<boolean>;
    deleteSignal(id: SignalId): Promise<boolean>;
    getActiveSubscriberCount(): Promise<bigint>;
    getCallerUserRole(): Promise<UserRole>;
    getMasterTemplate(): Promise<ExternalBlob | null>;
    getMyCertificates(): Promise<Array<CertificateRequestPublic>>;
    getMyPayments(): Promise<Array<PaymentPublic>>;
    getMySubscription(): Promise<SubscriptionPublic | null>;
    getTradeStats(): Promise<TradeStats>;
    getUpiConfig(): Promise<UpiConfigPublic>;
    hasCertificate(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listAllCertificateRequests(): Promise<Array<CertificateRequestPublic>>;
    listAllPayments(): Promise<Array<PaymentPublic>>;
    listPublicSuccessSignals(): Promise<Array<Signal>>;
    listSignals(): Promise<Array<Signal>>;
    markTradeOutcome(id: SignalId, status: Variant_success_failed, proofKey: string | null): Promise<Signal>;
    rejectCertificate(certId: CertificateId, rejectionReason: string | null): Promise<CertificateRequestPublic>;
    rejectPayment(id: PaymentId, reason: string): Promise<boolean>;
    selfRegister(): Promise<void>;
    submitCertificateRequest(fullName: string, state: string, country: string, email: string | null, experience: string | null, screenshot1: ExternalBlob, screenshot2: ExternalBlob | null, paymentScreenshot: ExternalBlob, utrNumber: string): Promise<CertificateRequestPublic>;
    submitPayment(screenshotBlob: ExternalBlob, utrNumber: string, senderName: string): Promise<PaymentPublic>;
    updateMasterTemplate(template: ExternalBlob): Promise<void>;
    updateQrCode(qrCodeBlob: ExternalBlob): Promise<void>;
    updateSignal(id: SignalId, input: SignalInput): Promise<boolean>;
    updateUpiId(upiId: string): Promise<void>;
    verifyAdminPassword(password: string): Promise<boolean>;
    verifyCertificate(certCode: string): Promise<CertificateRequestPublic | null>;
}
import type { AutoInjectData as _AutoInjectData, CertificateId as _CertificateId, CertificateRequestPublic as _CertificateRequestPublic, CertificateStatus as _CertificateStatus, ExternalBlob as _ExternalBlob, PaymentId as _PaymentId, PaymentPublic as _PaymentPublic, PaymentStatus as _PaymentStatus, Signal as _Signal, SignalId as _SignalId, SignalInput as _SignalInput, SignalType as _SignalType, SubscriptionPublic as _SubscriptionPublic, Timestamp as _Timestamp, TradeStatus as _TradeStatus, UpiConfigPublic as _UpiConfigPublic, UserId as _UserId, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async activateUserSubscription(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateUserSubscription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateUserSubscription(arg0);
            return result;
        }
    }
    async addSignal(arg0: SignalInput): Promise<Signal> {
        if (this.processError) {
            try {
                const result = await this.actor.addSignal(to_candid_SignalInput_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Signal_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSignal(to_candid_SignalInput_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Signal_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveCertificate(arg0: CertificateId, arg1: ExternalBlob | null): Promise<CertificateRequestPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.approveCertificate(arg0, await to_candid_opt_n21(this._uploadFile, this._downloadFile, arg1));
                return from_candid_CertificateRequestPublic_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveCertificate(arg0, await to_candid_opt_n21(this._uploadFile, this._downloadFile, arg1));
            return from_candid_CertificateRequestPublic_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async approvePayment(arg0: PaymentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approvePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approvePayment(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n30(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n30(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkSubscriptionStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkSubscriptionStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkSubscriptionStatus();
            return result;
        }
    }
    async claimAdminRole(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAdminRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAdminRole(arg0);
            return result;
        }
    }
    async deleteSignal(arg0: SignalId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSignal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSignal(arg0);
            return result;
        }
    }
    async getActiveSubscriberCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveSubscriberCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveSubscriberCount();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMasterTemplate(): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMasterTemplate();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMasterTemplate();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyCertificates(): Promise<Array<CertificateRequestPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCertificates();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCertificates();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPayments(): Promise<Array<PaymentPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPayments();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPayments();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySubscription(): Promise<SubscriptionPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubscription();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubscription();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradeStats(): Promise<TradeStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradeStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradeStats();
            return result;
        }
    }
    async getUpiConfig(): Promise<UpiConfigPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpiConfig();
                return from_candid_UpiConfigPublic_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpiConfig();
            return from_candid_UpiConfigPublic_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasCertificate(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasCertificate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasCertificate();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllCertificateRequests(): Promise<Array<CertificateRequestPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllCertificateRequests();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllCertificateRequests();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllPayments(): Promise<Array<PaymentPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllPayments();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllPayments();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPublicSuccessSignals(): Promise<Array<Signal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPublicSuccessSignals();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPublicSuccessSignals();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSignals(): Promise<Array<Signal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSignals();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSignals();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async markTradeOutcome(arg0: SignalId, arg1: Variant_success_failed, arg2: string | null): Promise<Signal> {
        if (this.processError) {
            try {
                const result = await this.actor.markTradeOutcome(arg0, to_candid_variant_n43(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n44(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Signal_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markTradeOutcome(arg0, to_candid_variant_n43(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n44(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Signal_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectCertificate(arg0: CertificateId, arg1: string | null): Promise<CertificateRequestPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectCertificate(arg0, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg1));
                return from_candid_CertificateRequestPublic_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectCertificate(arg0, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg1));
            return from_candid_CertificateRequestPublic_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectPayment(arg0: PaymentId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectPayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectPayment(arg0, arg1);
            return result;
        }
    }
    async selfRegister(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.selfRegister();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selfRegister();
            return result;
        }
    }
    async submitCertificateRequest(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: string | null, arg5: ExternalBlob, arg6: ExternalBlob | null, arg7: ExternalBlob, arg8: string): Promise<CertificateRequestPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCertificateRequest(arg0, arg1, arg2, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n44(this._uploadFile, this._downloadFile, arg4), await to_candid_ExternalBlob_n22(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n21(this._uploadFile, this._downloadFile, arg6), await to_candid_ExternalBlob_n22(this._uploadFile, this._downloadFile, arg7), arg8);
                return from_candid_CertificateRequestPublic_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCertificateRequest(arg0, arg1, arg2, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n44(this._uploadFile, this._downloadFile, arg4), await to_candid_ExternalBlob_n22(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n21(this._uploadFile, this._downloadFile, arg6), await to_candid_ExternalBlob_n22(this._uploadFile, this._downloadFile, arg7), arg8);
            return from_candid_CertificateRequestPublic_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitPayment(arg0: ExternalBlob, arg1: string, arg2: string): Promise<PaymentPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPayment(await to_candid_ExternalBlob_n22(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_PaymentPublic_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPayment(await to_candid_ExternalBlob_n22(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_PaymentPublic_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMasterTemplate(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMasterTemplate(await to_candid_ExternalBlob_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMasterTemplate(await to_candid_ExternalBlob_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateQrCode(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQrCode(await to_candid_ExternalBlob_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQrCode(await to_candid_ExternalBlob_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSignal(arg0: SignalId, arg1: SignalInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSignal(arg0, to_candid_SignalInput_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSignal(arg0, to_candid_SignalInput_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateUpiId(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUpiId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUpiId(arg0);
            return result;
        }
    }
    async verifyAdminPassword(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminPassword(arg0);
            return result;
        }
    }
    async verifyCertificate(arg0: string): Promise<CertificateRequestPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyCertificate(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyCertificate(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_CertificateRequestPublic_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CertificateRequestPublic): Promise<CertificateRequestPublic> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_CertificateStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CertificateStatus): CertificateStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_PaymentPublic_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentPublic): Promise<PaymentPublic> {
    return await from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_SignalType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalType): SignalType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Signal_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Signal): Signal {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_TradeStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeStatus): TradeStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_UpiConfigPublic_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UpiConfigPublic): Promise<UpiConfigPublic> {
    return await from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AutoInjectData]): AutoInjectData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubscriptionPublic]): SubscriptionPublic | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CertificateRequestPublic]): Promise<CertificateRequestPublic | null> {
    return value.length === 0 ? null : await from_candid_CertificateRequestPublic_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SignalId;
    proofKey: [] | [string];
    takeProfit: number;
    screenshotKey: [] | [string];
    pair: string;
    isActive: boolean;
    stopLoss: number;
    timestamp: _Timestamp;
    entryPrice: number;
    confidence: bigint;
    tradeStatus: _TradeStatus;
    signalType: _SignalType;
}): {
    id: SignalId;
    proofKey?: string;
    takeProfit: number;
    screenshotKey?: string;
    pair: string;
    isActive: boolean;
    stopLoss: number;
    timestamp: Timestamp;
    entryPrice: number;
    confidence: bigint;
    tradeStatus: TradeStatus;
    signalType: SignalType;
} {
    return {
        id: value.id,
        proofKey: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.proofKey)),
        takeProfit: value.takeProfit,
        screenshotKey: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.screenshotKey)),
        pair: value.pair,
        isActive: value.isActive,
        stopLoss: value.stopLoss,
        timestamp: value.timestamp,
        entryPrice: value.entryPrice,
        confidence: value.confidence,
        tradeStatus: from_candid_TradeStatus_n17(_uploadFile, _downloadFile, value.tradeStatus),
        signalType: from_candid_SignalType_n19(_uploadFile, _downloadFile, value.signalType)
    };
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CertificateId;
    status: _CertificateStatus;
    paymentScreenshot: _ExternalBlob;
    certCode: string;
    certificate: [] | [_ExternalBlob];
    country: string;
    userId: _UserId;
    createdAt: _Timestamp;
    rejectionReason: [] | [string];
    fullName: string;
    autoInjectData: [] | [_AutoInjectData];
    email: [] | [string];
    autoGenerated: boolean;
    experience: [] | [string];
    updatedAt: _Timestamp;
    state: string;
    screenshot1: _ExternalBlob;
    screenshot2: [] | [_ExternalBlob];
    utrNumber: string;
    paymentAmount: bigint;
}): Promise<{
    id: CertificateId;
    status: CertificateStatus;
    paymentScreenshot: ExternalBlob;
    certCode: string;
    certificate?: ExternalBlob;
    country: string;
    userId: UserId;
    createdAt: Timestamp;
    rejectionReason?: string;
    fullName: string;
    autoInjectData?: AutoInjectData;
    email?: string;
    autoGenerated: boolean;
    experience?: string;
    updatedAt: Timestamp;
    state: string;
    screenshot1: ExternalBlob;
    screenshot2?: ExternalBlob;
    utrNumber: string;
    paymentAmount: bigint;
}> {
    return {
        id: value.id,
        status: from_candid_CertificateStatus_n25(_uploadFile, _downloadFile, value.status),
        paymentScreenshot: await from_candid_ExternalBlob_n27(_uploadFile, _downloadFile, value.paymentScreenshot),
        certCode: value.certCode,
        certificate: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.certificate)),
        country: value.country,
        userId: value.userId,
        createdAt: value.createdAt,
        rejectionReason: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.rejectionReason)),
        fullName: value.fullName,
        autoInjectData: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.autoInjectData)),
        email: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.email)),
        autoGenerated: value.autoGenerated,
        experience: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.experience)),
        updatedAt: value.updatedAt,
        state: value.state,
        screenshot1: await from_candid_ExternalBlob_n27(_uploadFile, _downloadFile, value.screenshot1),
        screenshot2: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.screenshot2)),
        utrNumber: value.utrNumber,
        paymentAmount: value.paymentAmount
    };
}
async function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PaymentId;
    status: _PaymentStatus;
    userId: _UserId;
    rejectionReason: [] | [string];
    timestamp: _Timestamp;
    senderName: string;
    utrNumber: string;
    screenshotBlob: _ExternalBlob;
}): Promise<{
    id: PaymentId;
    status: PaymentStatus;
    userId: UserId;
    rejectionReason?: string;
    timestamp: Timestamp;
    senderName: string;
    utrNumber: string;
    screenshotBlob: ExternalBlob;
}> {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n38(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        rejectionReason: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.rejectionReason)),
        timestamp: value.timestamp,
        senderName: value.senderName,
        utrNumber: value.utrNumber,
        screenshotBlob: await from_candid_ExternalBlob_n27(_uploadFile, _downloadFile, value.screenshotBlob)
    };
}
async function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    qrCodeBlob: [] | [_ExternalBlob];
    upiId: string;
}): Promise<{
    qrCodeBlob?: ExternalBlob;
    upiId: string;
}> {
    return {
        qrCodeBlob: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.qrCodeBlob)),
        upiId: value.upiId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    success: null;
} | {
    failed: null;
}): TradeStatus {
    return "pending" in value ? TradeStatus.pending : "success" in value ? TradeStatus.success : "failed" in value ? TradeStatus.failed : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): SignalType {
    return "buy" in value ? SignalType.buy : "sell" in value ? SignalType.sell : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): CertificateStatus {
    return "pending" in value ? CertificateStatus.pending : "approved" in value ? CertificateStatus.approved : "rejected" in value ? CertificateStatus.rejected : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CertificateRequestPublic>): Promise<Array<CertificateRequestPublic>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CertificateRequestPublic_n23(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentPublic>): Promise<Array<PaymentPublic>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PaymentPublic_n36(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Signal>): Array<Signal> {
    return value.map((x)=>from_candid_Signal_n14(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_SignalInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalInput): _SignalInput {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_SignalType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalType): _SignalType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_TradeStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeStatus): _TradeStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    takeProfit: number;
    screenshotKey?: string;
    pair: string;
    stopLoss: number;
    entryPrice: number;
    confidence: bigint;
    tradeStatus?: TradeStatus;
    signalType: SignalType;
}): {
    takeProfit: number;
    screenshotKey: [] | [string];
    pair: string;
    stopLoss: number;
    entryPrice: number;
    confidence: bigint;
    tradeStatus: [] | [_TradeStatus];
    signalType: _SignalType;
} {
    return {
        takeProfit: value.takeProfit,
        screenshotKey: value.screenshotKey ? candid_some(value.screenshotKey) : candid_none(),
        pair: value.pair,
        stopLoss: value.stopLoss,
        entryPrice: value.entryPrice,
        confidence: value.confidence,
        tradeStatus: value.tradeStatus ? candid_some(to_candid_TradeStatus_n10(_uploadFile, _downloadFile, value.tradeStatus)) : candid_none(),
        signalType: to_candid_SignalType_n12(_uploadFile, _downloadFile, value.signalType)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeStatus): {
    pending: null;
} | {
    success: null;
} | {
    failed: null;
} {
    return value == TradeStatus.pending ? {
        pending: null
    } : value == TradeStatus.success ? {
        success: null
    } : value == TradeStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalType): {
    buy: null;
} | {
    sell: null;
} {
    return value == SignalType.buy ? {
        buy: null
    } : value == SignalType.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_success_failed): {
    success: null;
} | {
    failed: null;
} {
    return value == Variant_success_failed.success ? {
        success: null
    } : value == Variant_success_failed.failed ? {
        failed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
