import type { Principal } from "@icp-sdk/core/principal";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
export class ExternalBlob {
    getBytes(): Promise<Uint8Array<ArrayBuffer>>;
    getDirectURL(): string;
    static fromURL(url: string): ExternalBlob;
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob;
    withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob;
}
export interface Signal {
    id: SignalId;
    proofKey?: string;
    takeProfit: number;
    screenshotKey?: string;
    pair: string;
    isActive: boolean;
    stopLoss: number;
    timestamp: Timestamp;
    entryPrice: number;
    confidence: bigint;
    tradeStatus: TradeStatus;
    signalType: SignalType;
}
export interface AutoInjectData {
    issueDate: string;
    certCode: string;
    fullName: string;
}
export type Timestamp = bigint;
export type SignalId = bigint;
export interface SignalInput {
    takeProfit: number;
    screenshotKey?: string;
    pair: string;
    stopLoss: number;
    entryPrice: number;
    confidence: bigint;
    tradeStatus?: TradeStatus;
    signalType: SignalType;
}
export interface PaymentPublic {
    id: PaymentId;
    status: PaymentStatus;
    userId: UserId;
    rejectionReason?: string;
    timestamp: Timestamp;
    senderName: string;
    utrNumber: string;
    screenshotBlob: ExternalBlob;
}
export interface UpiConfigPublic {
    qrCodeBlob?: ExternalBlob;
    upiId: string;
}
export interface CertificateRequestPublic {
    id: CertificateId;
    status: CertificateStatus;
    paymentScreenshot: ExternalBlob;
    certCode: string;
    certificate?: ExternalBlob;
    country: string;
    userId: UserId;
    createdAt: Timestamp;
    rejectionReason?: string;
    fullName: string;
    autoInjectData?: AutoInjectData;
    email?: string;
    autoGenerated: boolean;
    experience?: string;
    updatedAt: Timestamp;
    state: string;
    screenshot1: ExternalBlob;
    screenshot2?: ExternalBlob;
    utrNumber: string;
    paymentAmount: bigint;
}
export type UserId = Principal;
export interface TradeStats {
    failedSignals: bigint;
    winRate: number;
    totalSignals: bigint;
    successSignals: bigint;
}
export type CertificateId = bigint;
export type PaymentId = bigint;
export interface SubscriptionPublic {
    expiresAt: Timestamp;
    userId: UserId;
    isActive: boolean;
}
export enum CertificateStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum SignalType {
    buy = "buy",
    sell = "sell"
}
export enum TradeStatus {
    pending = "pending",
    success = "success",
    failed = "failed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_success_failed {
    success = "success",
    failed = "failed"
}
export interface backendInterface {
    activateUserSubscription(userId: UserId): Promise<void>;
    addSignal(input: SignalInput): Promise<Signal>;
    approveCertificate(certId: CertificateId, customCertificate: ExternalBlob | null): Promise<CertificateRequestPublic>;
    approvePayment(id: PaymentId): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkSubscriptionStatus(): Promise<boolean>;
    claimAdminRole(password: string): Promise<boolean>;
    deleteSignal(id: SignalId): Promise<boolean>;
    getActiveSubscriberCount(): Promise<bigint>;
    getCallerUserRole(): Promise<UserRole>;
    getMasterTemplate(): Promise<ExternalBlob | null>;
    getMyCertificates(): Promise<Array<CertificateRequestPublic>>;
    getMyPayments(): Promise<Array<PaymentPublic>>;
    getMySubscription(): Promise<SubscriptionPublic | null>;
    getTradeStats(): Promise<TradeStats>;
    getUpiConfig(): Promise<UpiConfigPublic>;
    hasCertificate(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listAllCertificateRequests(): Promise<Array<CertificateRequestPublic>>;
    listAllPayments(): Promise<Array<PaymentPublic>>;
    listPublicSuccessSignals(): Promise<Array<Signal>>;
    listSignals(): Promise<Array<Signal>>;
    markTradeOutcome(id: SignalId, status: Variant_success_failed, proofKey: string | null): Promise<Signal>;
    rejectCertificate(certId: CertificateId, rejectionReason: string | null): Promise<CertificateRequestPublic>;
    rejectPayment(id: PaymentId, reason: string): Promise<boolean>;
    selfRegister(): Promise<void>;
    submitCertificateRequest(fullName: string, state: string, country: string, email: string | null, experience: string | null, screenshot1: ExternalBlob, screenshot2: ExternalBlob | null, paymentScreenshot: ExternalBlob, utrNumber: string): Promise<CertificateRequestPublic>;
    submitPayment(screenshotBlob: ExternalBlob, utrNumber: string, senderName: string): Promise<PaymentPublic>;
    updateMasterTemplate(template: ExternalBlob): Promise<void>;
    updateQrCode(qrCodeBlob: ExternalBlob): Promise<void>;
    updateSignal(id: SignalId, input: SignalInput): Promise<boolean>;
    updateUpiId(upiId: string): Promise<void>;
    verifyAdminPassword(password: string): Promise<boolean>;
    verifyCertificate(certCode: string): Promise<CertificateRequestPublic | null>;
}
