/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ServiceId = bigint;
export type LeadId = bigint;
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface SocialLink {
    url: string;
    platform: string;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface SubmitOrderRequest {
    cryptoType: string;
    cryptoSymbol: string;
    screenshotUrl: string;
    network: string;
    walletAddress: string;
}
export interface Service {
    id: ServiceId;
    title: string;
    sortOrder: bigint;
    description: string;
    iconName: string;
}
export interface HeroContent {
    headline: string;
    ctaText: string;
    ctaSubtext: string;
    subtitle: string;
}
export interface WhyChooseSection {
    title: string;
    features: Array<WhyChooseFeature>;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Lead {
    id: LeadId;
    fullName: string;
    timestamp: bigint;
    contactNumber: string;
}
export interface FooterLink {
    url: string;
    text: string;
}
export interface FooterContent {
    links: Array<FooterLink>;
    copyright: string;
}
export interface ButtonLabels {
    whatsappButtonText: string;
    supportButtonText: string;
}
export interface CryptoListing {
    id: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    price: number;
    symbol: string;
}
export interface AppSettings {
    walletNetwork: string;
    walletAddress: string;
    currency: Currency;
    upiId: string;
    paymentType: PaymentType;
    heroContent: HeroContent;
    footerContent: FooterContent;
    whyChoose: WhyChooseSection;
    buttonLabels: ButtonLabels;
}
export interface ContactDetails {
    whatsapp: string;
    email: string;
    address: string;
    phone: string;
    socialMedia: Array<SocialLink>;
}
export interface CryptoOrderPublic {
    id: bigint;
    status: OrderStatus;
    completedAt?: bigint;
    cryptoType: string;
    cryptoSymbol: string;
    userId: Principal;
    screenshotUrl: string;
    createdAt: bigint;
    network: string;
    walletAddress: string;
    reviewComment: string;
    reviewStatus: ReviewStatus;
}
export interface WhyChooseFeature {
    title: string;
    icon: string;
    description: string;
}
export enum Currency {
    INR = "INR",
    USD = "USD"
}
export enum OrderStatus {
    pending = "pending",
    completed = "completed",
    rejected = "rejected"
}
export enum PaymentType {
    UPI = "UPI",
    CryptoWallet = "CryptoWallet"
}
export enum ReviewStatus {
    trusted = "trusted",
    none = "none",
    notTrusted = "notTrusted"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addService(title: string, description: string, iconName: string, sortOrder: bigint): Promise<Service>;
    adminAddCryptoListing(name: string, symbol: string, description: string, price: number): Promise<bigint>;
    adminCompleteOrder(id: bigint): Promise<boolean>;
    adminDeleteCryptoListing(id: bigint): Promise<boolean>;
    adminListAllCryptoListings(): Promise<Array<CryptoListing>>;
    adminListAllOrders(): Promise<Array<CryptoOrderPublic>>;
    adminListPendingOrders(): Promise<Array<CryptoOrderPublic>>;
    adminRejectOrder(id: bigint): Promise<boolean>;
    adminUpdateCryptoListing(id: bigint, name: string, symbol: string, description: string, price: number, isActive: boolean): Promise<boolean>;
    adminUpdateSettings(settings: AppSettings): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    captureLead(fullName: string, contactNumber: string): Promise<Lead>;
    claimAdminRole(password: string): Promise<boolean>;
    deleteLead(id: LeadId): Promise<boolean>;
    deleteService(id: ServiceId): Promise<boolean>;
    getAppSettings(): Promise<AppSettings>;
    getCallerUserRole(): Promise<UserRole>;
    getContactDetails(): Promise<ContactDetails | null>;
    getCryptoListing(id: bigint): Promise<CryptoListing | null>;
    getLead(id: LeadId): Promise<Lead | null>;
    getMyOrders(): Promise<Array<CryptoOrderPublic>>;
    getService(id: ServiceId): Promise<Service | null>;
    isCallerAdmin(): Promise<boolean>;
    listActiveCryptoListings(): Promise<Array<CryptoListing>>;
    listLeads(): Promise<Array<Lead>>;
    listServices(): Promise<Array<Service>>;
    pollNewlyCompletedOrders(): Promise<Array<CryptoOrderPublic>>;
    selfRegister(): Promise<void>;
    setContactDetails(phone: string, whatsapp: string, email: string, address: string, socialMedia: Array<SocialLink>): Promise<ContactDetails>;
    submitCryptoOrder(req: SubmitOrderRequest): Promise<bigint>;
    submitOrderReview(orderId: bigint, reviewStatus: ReviewStatus, comment: string): Promise<boolean>;
    updateService(id: ServiceId, title: string, description: string, iconName: string, sortOrder: bigint): Promise<Service | null>;
    verifyAdminPassword(password: string): Promise<boolean>;
}
import type { AppSettings as _AppSettings, ButtonLabels as _ButtonLabels, ContactDetails as _ContactDetails, CryptoListing as _CryptoListing, CryptoOrderPublic as _CryptoOrderPublic, Currency as _Currency, FooterContent as _FooterContent, HeroContent as _HeroContent, Lead as _Lead, OrderStatus as _OrderStatus, PaymentType as _PaymentType, ReviewStatus as _ReviewStatus, Service as _Service, UserRole as _UserRole, WhyChooseSection as _WhyChooseSection, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addService(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<Service> {
        if (this.processError) {
            try {
                const result = await this.actor.addService(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addService(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async adminAddCryptoListing(arg0: string, arg1: string, arg2: string, arg3: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddCryptoListing(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddCryptoListing(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async adminCompleteOrder(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCompleteOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCompleteOrder(arg0);
            return result;
        }
    }
    async adminDeleteCryptoListing(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteCryptoListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteCryptoListing(arg0);
            return result;
        }
    }
    async adminListAllCryptoListings(): Promise<Array<CryptoListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListAllCryptoListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListAllCryptoListings();
            return result;
        }
    }
    async adminListAllOrders(): Promise<Array<CryptoOrderPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListAllOrders();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListAllOrders();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListPendingOrders(): Promise<Array<CryptoOrderPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListPendingOrders();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListPendingOrders();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRejectOrder(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRejectOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRejectOrder(arg0);
            return result;
        }
    }
    async adminUpdateCryptoListing(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: number, arg5: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateCryptoListing(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateCryptoListing(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async adminUpdateSettings(arg0: AppSettings): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateSettings(to_candid_AppSettings_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateSettings(to_candid_AppSettings_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async captureLead(arg0: string, arg1: string): Promise<Lead> {
        if (this.processError) {
            try {
                const result = await this.actor.captureLead(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.captureLead(arg0, arg1);
            return result;
        }
    }
    async claimAdminRole(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAdminRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAdminRole(arg0);
            return result;
        }
    }
    async deleteLead(arg0: LeadId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLead(arg0);
            return result;
        }
    }
    async deleteService(arg0: ServiceId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteService(arg0);
            return result;
        }
    }
    async getAppSettings(): Promise<AppSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppSettings();
                return from_candid_AppSettings_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppSettings();
            return from_candid_AppSettings_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactDetails(): Promise<ContactDetails | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactDetails();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactDetails();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCryptoListing(arg0: bigint): Promise<CryptoListing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCryptoListing(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCryptoListing(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLead(arg0: LeadId): Promise<Lead | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLead(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLead(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrders(): Promise<Array<CryptoOrderPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getService(arg0: ServiceId): Promise<Service | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listActiveCryptoListings(): Promise<Array<CryptoListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActiveCryptoListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActiveCryptoListings();
            return result;
        }
    }
    async listLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLeads();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLeads();
            return result;
        }
    }
    async listServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.listServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listServices();
            return result;
        }
    }
    async pollNewlyCompletedOrders(): Promise<Array<CryptoOrderPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.pollNewlyCompletedOrders();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pollNewlyCompletedOrders();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async selfRegister(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.selfRegister();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selfRegister();
            return result;
        }
    }
    async setContactDetails(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<SocialLink>): Promise<ContactDetails> {
        if (this.processError) {
            try {
                const result = await this.actor.setContactDetails(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setContactDetails(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async submitCryptoOrder(arg0: SubmitOrderRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCryptoOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCryptoOrder(arg0);
            return result;
        }
    }
    async submitOrderReview(arg0: bigint, arg1: ReviewStatus, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.submitOrderReview(arg0, to_candid_ReviewStatus_n36(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitOrderReview(arg0, to_candid_ReviewStatus_n36(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async updateService(arg0: ServiceId, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<Service | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0, arg1, arg2, arg3, arg4);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0, arg1, arg2, arg3, arg4);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyAdminPassword(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminPassword(arg0);
            return result;
        }
    }
}
function from_candid_AppSettings_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppSettings): AppSettings {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_CryptoOrderPublic_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CryptoOrderPublic): CryptoOrderPublic {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Currency_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Currency): Currency {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentType): PaymentType {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_ReviewStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReviewStatus): ReviewStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContactDetails]): ContactDetails | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CryptoListing]): CryptoListing | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Lead]): Lead | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Service]): Service | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    completedAt: [] | [bigint];
    cryptoType: string;
    cryptoSymbol: string;
    userId: Principal;
    screenshotUrl: string;
    createdAt: bigint;
    network: string;
    walletAddress: string;
    reviewComment: string;
    reviewStatus: _ReviewStatus;
}): {
    id: bigint;
    status: OrderStatus;
    completedAt?: bigint;
    cryptoType: string;
    cryptoSymbol: string;
    userId: Principal;
    screenshotUrl: string;
    createdAt: bigint;
    network: string;
    walletAddress: string;
    reviewComment: string;
    reviewStatus: ReviewStatus;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n11(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.completedAt)),
        cryptoType: value.cryptoType,
        cryptoSymbol: value.cryptoSymbol,
        userId: value.userId,
        screenshotUrl: value.screenshotUrl,
        createdAt: value.createdAt,
        network: value.network,
        walletAddress: value.walletAddress,
        reviewComment: value.reviewComment,
        reviewStatus: from_candid_ReviewStatus_n14(_uploadFile, _downloadFile, value.reviewStatus)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    walletNetwork: string;
    walletAddress: string;
    currency: _Currency;
    upiId: string;
    paymentType: _PaymentType;
    heroContent: _HeroContent;
    footerContent: _FooterContent;
    whyChoose: _WhyChooseSection;
    buttonLabels: _ButtonLabels;
}): {
    walletNetwork: string;
    walletAddress: string;
    currency: Currency;
    upiId: string;
    paymentType: PaymentType;
    heroContent: HeroContent;
    footerContent: FooterContent;
    whyChoose: WhyChooseSection;
    buttonLabels: ButtonLabels;
} {
    return {
        walletNetwork: value.walletNetwork,
        walletAddress: value.walletAddress,
        currency: from_candid_Currency_n26(_uploadFile, _downloadFile, value.currency),
        upiId: value.upiId,
        paymentType: from_candid_PaymentType_n28(_uploadFile, _downloadFile, value.paymentType),
        heroContent: value.heroContent,
        footerContent: value.footerContent,
        whyChoose: value.whyChoose,
        buttonLabels: value.buttonLabels
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    rejected: null;
}): OrderStatus {
    return "pending" in value ? OrderStatus.pending : "completed" in value ? OrderStatus.completed : "rejected" in value ? OrderStatus.rejected : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trusted: null;
} | {
    none: null;
} | {
    notTrusted: null;
}): ReviewStatus {
    return "trusted" in value ? ReviewStatus.trusted : "none" in value ? ReviewStatus.none : "notTrusted" in value ? ReviewStatus.notTrusted : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    INR: null;
} | {
    USD: null;
}): Currency {
    return "INR" in value ? Currency.INR : "USD" in value ? Currency.USD : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    UPI: null;
} | {
    CryptoWallet: null;
}): PaymentType {
    return "UPI" in value ? PaymentType.UPI : "CryptoWallet" in value ? PaymentType.CryptoWallet : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CryptoOrderPublic>): Array<CryptoOrderPublic> {
    return value.map((x)=>from_candid_CryptoOrderPublic_n9(_uploadFile, _downloadFile, x));
}
function to_candid_AppSettings_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppSettings): _AppSettings {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Currency_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Currency): _Currency {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentType): _PaymentType {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_ReviewStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewStatus): _ReviewStatus {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    walletNetwork: string;
    walletAddress: string;
    currency: Currency;
    upiId: string;
    paymentType: PaymentType;
    heroContent: HeroContent;
    footerContent: FooterContent;
    whyChoose: WhyChooseSection;
    buttonLabels: ButtonLabels;
}): {
    walletNetwork: string;
    walletAddress: string;
    currency: _Currency;
    upiId: string;
    paymentType: _PaymentType;
    heroContent: _HeroContent;
    footerContent: _FooterContent;
    whyChoose: _WhyChooseSection;
    buttonLabels: _ButtonLabels;
} {
    return {
        walletNetwork: value.walletNetwork,
        walletAddress: value.walletAddress,
        currency: to_candid_Currency_n18(_uploadFile, _downloadFile, value.currency),
        upiId: value.upiId,
        paymentType: to_candid_PaymentType_n20(_uploadFile, _downloadFile, value.paymentType),
        heroContent: value.heroContent,
        footerContent: value.footerContent,
        whyChoose: value.whyChoose,
        buttonLabels: value.buttonLabels
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Currency): {
    INR: null;
} | {
    USD: null;
} {
    return value == Currency.INR ? {
        INR: null
    } : value == Currency.USD ? {
        USD: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentType): {
    UPI: null;
} | {
    CryptoWallet: null;
} {
    return value == PaymentType.UPI ? {
        UPI: null
    } : value == PaymentType.CryptoWallet ? {
        CryptoWallet: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewStatus): {
    trusted: null;
} | {
    none: null;
} | {
    notTrusted: null;
} {
    return value == ReviewStatus.trusted ? {
        trusted: null
    } : value == ReviewStatus.none ? {
        none: null
    } : value == ReviewStatus.notTrusted ? {
        notTrusted: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
